.gitignore
insights_hsdm_api/package.json
package-lock.json
package.json
topological_inventory-api/package.json

Update the superagent version in the swagger client generated code.Remove package-lock from gitignore.

Update the superagent version in the swagger client generated code

---

.travis/deploy.sh

Deployment fixes

---

src/Helpers/Portfolio/PortfolioHelper.js
src/Routes.js
src/SmartComponents/Common/AddPortfolioModal.js
src/SmartComponents/ServicePortal/PortalDashboard.js
src/SmartComponents/ServicePortal/PortalNav.js

Update create portfolio and portfolio Items API. Updated package.json for regenerated api client code
Fixed routes modified by the Edit Portfolio PR https://github.com/ManageIQ/service_portal-ui/pull/9

Update create portfolio and portfolio Items API

---

package-lock.json

Updated package-lock.json after adding version to the swagger client

Updated package-lock.json after adding version to the swagger client

---

src/SmartComponents/ServicePortal/PortalNav.js

Update Navigation list for empty platform/portfolio list 
Remove the Edit icon in the navigation list as it is removed from the new UX design.

Update Navigation list for empty platform/portfolio list 

---

src/SmartComponents/ServicePortal/PortalNav.js

Follow up to https://github.com/ManageIQ/service_portal-ui/pull/16

Update for the platform navigation list 

---

.travis.yml
package.json

Changes to use the new insights-dev Jenkins

Changes to use the new insights-dev Jenkins

---

.gitignore
.travis/custom_release.sh
config/webpack.common.js
src/Routes.js

@gmcculloug Please review.
@lgalis This includes the change for the service_portal const.

More fixes for deployment

---

config/dev.webpack.config.js

Revert commit 89844d6118d0519398643adaadf30e581f63ad42

Revert the enabling of hot-reloading

---

src/App.js
src/constants/ui-constants.js

Stretched navigation min height from to bottom of the screen to match designs.

Fixed menu min height to stretch from top to bottom.

---

src/SmartComponents/ServicePortal/PortalNav.js
src/SmartComponents/ServicePortal/portalnav.scss

- Highlight active link
- No longer reloading nav on each link change

Fix navigation

---

src/App.scss
src/PresentationalComponents/Platform/PlatformItem.js
src/PresentationalComponents/Portfolio/PorfolioCard.js
src/PresentationalComponents/Portfolio/portfolio-card-header.js
src/PresentationalComponents/Portfolio/portfoliocard.scss
src/PresentationalComponents/Shared/ImageWithDefault.js
src/SmartComponents/Order/OrderServiceFormStepInformation.js
src/SmartComponents/Portfolio/PortfolioItem.js

Added styling to portfolio card to match designs from https://redhat.invisionapp.com/share/6NPCR8DYP7F#/screens/333946777/comments.
Buttons don't do anything right now.

Added styling to portfolio card.

---

src/Helpers/Order/OrderHelper.js
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js

Updated type for servicePlans.

Add back the addToOrder call removed by refactoring

---

src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
src/PresentationalComponents/Shared/OrderToolbarItem.js

The order list component is only listing the content of the Orders table. The UX design for the Orders status will be done in a separate PR.

Connect the cart button to the Order list component

---

src/SmartComponents/ContentGallery/ContentList.js

Sort descending by create date

Sort orders by descending create date

---

src/SmartComponents/Common/AddPortfolioModal.js

Restore the refresh portfolio list after add - this was removed during refactoring

Restore portfolio list refresh when adding a portfolio.

---

src/SmartComponents/Common/EditPortfolioModal.js

Update Label for Portfolio Name

Update Label for Portfolio Name 

---

.gitignore
package-lock.json
package.json

... it was added during refactoring

Remove package-lock.json from gitignore

---

src/Helpers/Shared/Helper.js
src/Helpers/Shared/helpers.js
src/SmartComponents/Platform/Platform.js
src/SmartComponents/Platform/Platforms.js
src/SmartComponents/Portfolio/Portfolio.js
src/SmartComponents/Portfolio/Portfolios.js

Added automatic scroll to top of the page when changing portfolio/platform

Added automatic scroll to top on platform/portfolio change.

---

src/Utilities/Constants.js

Revert changes used locally for the topology service.

Revert changes for topology service path

---

src/PresentationalComponents/Portfolio/PortfoliosFilterToolbar.js
src/PresentationalComponents/Shared/FilterToolbarItem.js
src/SmartComponents/ContentGallery/ContentGallery.js
src/SmartComponents/Portfolio/Portfolios.js

Added filtering to portfolios screen

Added filtering of portfolios

---

src/PresentationalComponents/Portfolio/PorfolioCard.js
src/SmartComponents/Portfolio/Portfolios.js

Portfolio cards are now clickable and links to portfolio.

Add link to portfolio on card click.

---

src/App.scss
src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
src/SmartComponents/Platform/Platform.js
src/SmartComponents/Platform/Platforms.js
src/SmartComponents/Portfolio/Portfolio.js
src/SmartComponents/Portfolio/Portfolios.js

Cleaned up the toolbars, added single class that handle toolbar spacing.

Added correct spacing for action toolbars.

---

src/SmartComponents/Portfolio/PortfolioItem.js

Fixed displaying modal for ordering.
Wrong parameters were passed to redux action creator so it did bot update modal state correctly.

Added proper parameters to show modal actions.

---

package-lock.json
package.json
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js

Migrated the order form to data-driven-forms library. Adds PF4 styling.
Also removed the Mozilla form from dependencies because its no longer used anywhere.

Order data driven form

---

src/SmartComponents/Order/OrderServiceFormStepConfiguration.js

- fixes missing data parameter for `sendSubmitOrder ` function
- hooks `sendSubmitOrder` to dispatch

Added sendSubmitOrder to mapDispatchToProps and send correct data.

---

.travis.yml
config/setupTests.js
package-lock.json
package.json
src/Helpers/Portfolio/PortfolioHelper.js
src/redux/Actions/PortfolioActions.js
src/test/.eslintrc
src/test/redux/actions/portfolio-actions.test.js

Added initial setup for async testing. And also did some testing for portfolio actions so we have a reference for the future.

Tests for redux portfolio actions

---

package-lock.json
package.json
src/App.scss
src/Routes.js
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
src/SmartComponents/Order/Orders.js
src/SmartComponents/Order/orders-toolbar.js
src/SmartComponents/Order/orders.scss
src/test/redux/actions/portfolio-actions.test.js

Replaces the Insights table with PF4 data list to match design mocks. Is still mostly a placeholder but can be easily updated once we have necessary data.
Edit: I'm aware of the duplicate code. Will be resolved once we can differentiate between all orders and my orders.

Use PF4 data list to show orders.

---

src/Routes.js
src/index.html

Insights page layout will be changed a bit in a future. This PR prepares PF classes to transition once the changes in Chrome are ready. Has no effect right now.

Added new pf classes to app template.

---

package-lock.json
package.json
src/Utilities/Constants.js
src/redux/Actions/OrderActions.js
src/redux/Actions/PlatformActions.js
src/redux/Actions/PortfolioActions.js
src/test/redux/actions/platform-actions.test.js
src/test/redux/actions/portfolio-actions.test.js

Updated service catalog and topology API version to schema version 0.1.0
- locked js API client version to patch releases only (Bugfixes etc.)
- Pagination data is not stored yet. Will come later when we actually start paginate. It will required some redux store changes.

Update api 0.1.0

---

src/test/redux/reducers/platform-reducer.test.js
src/test/redux/redux-helpers.js

Adds tests for platform reducer function.

Added tests for platform reducer.

---

src/test/redux/reducers/order-reducer.test.js

Adds test for **Order Reducer**

Added tests for order reducer

---

.gitignore
.travis.yml
package.json

Adds test statistics check to pull requests.

Add codecov to travis.

---

src/redux/reducers/portfolioReducer.js
src/test/redux/reducers/portfolio-reducer.test.js

Added tests for portfolio reducer.

---

package-lock.json
package.json

I've updated/removed some dependencies that cause warnings about security vulnerabilities. More info about these errors can be found here: https://docs.npmjs.com/cli/audit

Fixed dependencies security vulnerabilities.

---

src/Helpers/Order/OrderHelper.js
src/test/redux/actions/order-actions.test.js

- submit order now also sends namespace value from order form.

Added real parameters to submit order action.

---

src/SmartComponents/Order/Orders.js

Orders are now sorted by date from newest do oldest directly in UI.

Sort orders from newest to oldest.

---

package-lock.json
package.json
src/Helpers/Order/OrderHelper.js
src/Helpers/Portfolio/PortfolioHelper.js
src/Helpers/Shared/helpers.js
src/PresentationalComponents/Portfolio/PorfolioCard.js
src/SmartComponents/Common/OrderModal.js
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
src/SmartComponents/Platform/Platform.js
src/SmartComponents/Portfolio/AddProductsToPortfolio.js
src/SmartComponents/Portfolio/Portfolio.js
src/test/redux/actions/order-actions.test.js
src/test/redux/actions/portfolio-actions.test.js

- Updates api client to match latest version
- Use custom portfolio items endpoint to get all the attributes
- Update service offering filters by `display_name` attribute and using `name` as fallback attribute
- Fixed closing modal after order submission

Update api client to match new routing.

---

package-lock.json
package.json
src/Helpers/Portfolio/PortfolioHelper.js
src/test/redux/actions/portfolio-actions.test.js

Adds latest API model form portfolio items.
API pr: https://github.com/ManageIQ/service_portal-api/pull/119

Update js client with correct portflio items model.

---

src/PresentationalComponents/Platform/PlatformCard.js
src/PresentationalComponents/Portfolio/PorfolioCard.js
src/SmartComponents/ContentGallery/ContentGallery.js
src/SmartComponents/Portfolio/PortfolioItem.js
src/test/presentional-components/platform/__snapshots__/platform-card.test.js.snap
src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap

Uses PF4 gallery component for portfolio/platforms cards lists.

Use gallery component for portfolio/platforms card layouts.

---

README.md
config/dev.webpack.config.js
config/webpack.common.js
package-lock.json
package.json
src/App.js
src/Helpers/Order/OrderHelper.js
src/Helpers/Portfolio/PortfolioHelper.js
src/Helpers/Shared/userLogin.js
src/Routes.js
src/SmartComponents/Catalog/Catalog.js
src/SmartComponents/Catalog/catalog.scss
src/Utilities/Constants.js
src/entry-dev.js
src/entry.js
src/index.html
src/redux/ActionTypes/UiActionTypes.js
src/test/helpers/shared/user-login.test.js
src/test/redux/actions/order-actions.test.js
src/test/redux/actions/portfolio-actions.test.js

This will depend on 
- The build repo being renamed
- ~~The swagger clients rebuilt.~~
@gmcculloug

Rename to catalog

---

package-lock.json
package.json
src/Helpers/Platform/PlatformHelper.js
src/Helpers/Shared/pagination.js
src/PresentationalComponents/Platform/PlatformToolbar.js
src/PresentationalComponents/Shared/LoaderPlaceholders.js
src/SmartComponents/Platform/Platform.js
src/SmartComponents/Portfolio/AddProductsToPortfolio.js
src/redux/Actions/PlatformActions.js
src/test/presentational-components/platform/__snapshots__/platform-toolbar.test.js.snap
src/test/presentional-components/shared/__snapshots__/loader-placeholders.test.js.snap
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
src/test/smart-components/platform/__snapshots__/platform.test.js.snap
src/test/smart-components/platform/platform.test.js

Added pagination for platform items. Its complete but just waiting for the API fix: https://github.com/ManageIQ/service_portal-api/pull/135 so i can make sure in the UI it does break anything even though we have covered it by tests.
- store meta information about platform items collection
- use non PF4 paging component (will be swapped once PF4 has working implementation)
- updated card placeholder for loading to match gallery layout.
- resolving dependency issues again

Platform pagination

---

config/dev.webpack.config.js
src/Helpers/Portfolio/PortfolioHelper.js
src/PresentationalComponents/Shared/LoaderPlaceholders.js
src/PresentationalComponents/Shared/breadcrubms.js
src/SmartComponents/Common/FormRenderer.js
src/SmartComponents/Common/OrderModal.js
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
src/SmartComponents/Portfolio/Portfolio.js
src/SmartComponents/Portfolio/PortfolioItem.js
src/SmartComponents/Portfolio/portfolio-item-detail.js
src/SmartComponents/products/portfolio-product.js
src/redux/Actions/PortfolioActions.js
src/test/redux/actions/portfolio-actions.test.js

Adds detail page form portfolio items. Show all currently available data.
Did not include test just yet because most of this is probably going to change.

Product detail page.

---

.travis/custom_release.sh
.travis/promote.sh

@gmcculloug Please review.  Not sure if this is the specific set we want to push to, but it's a start on the beta line.

Deploy to beta as well as stable

---

README.md
config/base.webpack.plugins.js
config/dev.webpack.config.js
config/spandx.config.js
config/webpack.common.js
src/entry-dev.js
src/entry.js
src/index.html

`sudo SPANDX_CONFIG="../service_portal-ui/config/spandx.config.js" bash scripts/run.sh`

Update routing based on new cloud navigation

---

config/base.webpack.plugins.js
config/setupTests.js
config/spandx.config.js

Update base path for APIs

---

src/PresentationalComponents/Platform/PlatformItem.js
src/PresentationalComponents/Shared/LoaderPlaceholders.js
src/PresentationalComponents/Shared/card-icon.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap

Adds icons to service offerings for both platform listing and while adding product to portfolio.

Added service offerings icons to UI.

---

src/SmartComponents/Common/OrderModal.js
src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
src/test/smart-components/order/order-service-form-step-configuration.test.js

- order modal did not close after submitting an order
fixes: https://projects.engineering.redhat.com/browse/SSP-245

Fixed missing URL for closing the order modal after submit.

---

src/redux/Actions/OrderActions.js
src/test/redux/actions/order-actions.test.js

- fixes missing notification after order success.
Fixes: https://projects.engineering.redhat.com/browse/SSP-249

Add missing notification after ordering success.

---

config/webpack.common.js

master is beta for deployment purposes

---

config/base.webpack.plugins.js
config/webpack.common.js
src/entry-dev.js
src/entry.js
src/index.html

This PR will enable beta routing with prefixing release to basename.

Enable beta routing via dynamic basename

---

config/webpack.common.js
package-lock.json
package.json
src/entry-dev.js
src/entry.js
src/helpers/order/order-helper.js
src/helpers/shared/user-login.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/portfolio/__snapshots__/remove-portfolio-items.test.js.snap
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/edit-toolbar-actions.test.js.snap
src/utilities/constants.js

- updated React Router dependency. Fixes console error with incorrect prop type.
- updated and replaced API client package
- trailing underscore in entry and entry-dev fiesl. Caused a crash in router with multiple childs
- cause: https://github.com/ManageIQ/catalog-ui/pull/136/files#diff-191158af9939fbb87d987e320a18d657R18
- incorrect attribute from packages json. Caused wrong resource path to JS and CSS resources
- cause: https://github.com/ManageIQ/catalog-ui/pull/136/files#diff-f737fedb5357468044db2dbe98eb0218R24
- added full API version number for catalog client. Caused post requests to have no effect (not even failed).
- cause: https://github.com/ManageIQ/catalog-ui/pull/137/files#diff-fb2187d73d464fdeb11eec6457b47760R1

Fixed ui not rendering.

---

package-lock.json
package.json
src/helpers/approval/approval-helper.js
src/helpers/shared/user-login.js
src/test/redux/actions/approval-actions.test.js
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js

- use approval api client from https://github.com/RedHatInsights/javascript-clients/tree/master/packages/approval

Use axios based approval client.

---

src/App.scss
src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/portfolio/portfolio-card-header.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/portfolio-card.test.js
src/utilities/constants.js

- added dropdown to portfolio card instead of buttons
- had to do some event catching in toolbar group because of PF behavior on the toggle button
- added date of last modification and owner of portfolio (should be replaced by actual account that changed it)

Added dropdown and last update date to portfolio card.

---

src/helpers/platform/platform-helper.js
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/platform/platform.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-pagination.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

Topology API introduced new filtering queries. The service offerings query has to be updated to return some results.

Fixed wrong query param for service offerings.

---

src/helpers/shared/helpers.js
src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/portfolio/portfolio-card-header.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/utilities/constants.js

- Removed background image from portfolio card.
- Changed modified date from date to `before x days`.

Updated portfolio card to match mocks.

---

package-lock.json
package.json
src/App.scss
src/presentational-components/shared/card-icon.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap

- added icons to portfolio items
- added icons to portfolio item detail
- added source icon to service if no icon is specified
- for now it defaults to openshift icon but will be changing based on provider once we have more.
- added lazy loading to images to increase performance
- network request for image will be fired only when the image is in view port

Portfolio items icons

---

src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/remove-portfolio-modal.js
src/smart-components/portfolio/share-portfolio-modal.js

Removed all notifications after canceling actions.

Removed all cancel actions notifications.

---

package-lock.json
package.json
src/helpers/order/order-helper.js
src/helpers/portfolio/portfolio-helper.js
src/helpers/share/share-helper.js
src/helpers/shared/user-login.js
src/test/helpers/shared/user-login.test.js

Updates the catalog client to work with the name spacing changes here: https://github.com/ManageIQ/catalog-api/pull/200
It would be great if someone can go and click through the app. I called every single catalog action and it works but i might have missed something.

Updated catalog js client.

---

src/smart-components/platform/platforms.js

Remove link from Settings text in empty state.

---

package.json

- fix missing env variable in prod build
cc @karelhala

Added missing env variable for prod build.

---

src/App.scss
src/constants/select-styles-override.js
src/presentational-components/portfolio/portfolio-order-toolbar.js
src/presentational-components/shared/filter-toolbar-item.js
src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
src/test/presentational-components/shared/filter-toolbar-item.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

- adjusted styling for filter elements on toolbars

Fixed styling for tollbar filter inputs.

---

src/redux/actions/order-actions.js
src/test/redux/actions/order-actions.test.js

- changed the orders order from newest to oldest.
cc @syncrou Can we add sorting to the API? its not critical just something that would be nice in future.

Fix orders order.

---

src/helpers/portfolio/portfolio-helper.js
src/redux/reducers/portfolio-reducer.js

- after updating portfolio from portfolio detail page, screen was not changed correctly with updated entity.
- title stayed the same for instance
- changes were applied after reload or navigating to different page and back.
- add update to redux state after successful portfolio update

Update redux state correctly after updating portfolio.

---

src/presentational-components/shared/card-common.js
src/presentational-components/shared/pf4-select-wrapper.js
src/smart-components/common/order-modal.js
src/smart-components/order/orders.js
src/smart-components/platform/platform.js
src/smart-components/portfolio/add-portfolio-modal.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/platform/platform-item.test.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
src/test/presentational-components/portfolio/portfolio-card.test.js
src/test/presentational-components/portfolio/portfolio-filter-toolbar.test.js
src/test/smart-components/order/orders.test.js
src/test/smart-components/platform/__snapshots__/platform.test.js.snap
src/test/smart-components/platform/platform.test.js
src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-to-portfolio.test.js.snap
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/item-detail-description.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
src/test/smart-components/portfolio/portfolio.test.js
src/test/smart-components/portfolio/portfolios.test.js
src/test/smart-components/portfolio/remove-portfolio-modal.test.js

- no changes to actual UI
- adds data to tests to remove console errors in tests
- mostly prop type validation
- missed async calls 
- fixes some prop type validation in certain components

Fix tests console errors.

---

src/smart-components/order/order-item.js

Adds id to order header.

---

package-lock.json
package.json

- Notifications no longer disappear after few seconds
- this was discussed with Susan
- notifications should not be hidden automatically but user has to close them manually
- changes was made here: https://github.com/RedHatInsights/insights-frontend-components/pull/390 to solve this globally
- notifications can be still configured to auto hide if we need

Update notifications middleware.

---

src/helpers/shared/user-login.js
src/test/smart-components/portfolio/portfolio.test.js
src/utilities/store.js

- adds and error interceptor that extracts response error body into object
- adds new keys to notifications error handling

Added axios error interceptor.

---

src/helpers/shared/helpers.js
src/smart-components/order/create-order-row.js
src/smart-components/order/order-detail-table.js
src/smart-components/order/order-item.js
src/test/smart-components/order/__snapshots__/order-detail-table.test.js.snap

- Added time to date time to relative order dates.
- Added time to the date time column
fixes: #177 

Added time and UTC tool tip for order relative dates.

---

src/presentational-components/shared/loader-placeholders.js
src/smart-components/order/orders.js
src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap

- added placeholder for Orders screen
- using empty data list with svg

Added correct placeholder to orders screen.

---

src/smart-components/order/create-order-row.js
src/smart-components/order/order-detail-table.js
src/smart-components/order/order-item.js
src/smart-components/order/order-messages-modal.js
src/smart-components/order/orders.js
src/test/smart-components/order/__snapshots__/order-detail-table.test.js.snap

- adds link to modal with order item progress messages
- we have no mocks for this so far, its mostly used for debugging right now

Added modal with progress messages.

---

src/index.html

Update title to just the App name

Update title to just the App name

---

package-lock.json
package.json

- UI blows up after creating an order
- there was an issue with notification component in insights fronted component
- updated to new version with fix

Update insights frontend components dependency.

---

src/smart-components/order/order-item.js
src/smart-components/order/orders.js

- added custom trigger for OrderItem render method
- Expanding/Collapsing the order item was slow
- When expanding every single order item was re-rendered
- added direct connection to redux from each order item
- added should component update trigger 
- render times are down from 125 ms to 15 ms per order item

Added custom render trigger on order item component.

---

src/forms/portfolio-form.schema.js
src/helpers/platform/platform-helper.js
src/helpers/portfolio/portfolio-helper.js
src/smart-components/portfolio/add-portfolio-modal.js
src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/utilities/async-form-validator.js

- added async name validation when creating/editing portfolios

Added async validation for portfolio name.

---

src/smart-components/order/create-order-row.js

- added labels to progress icons
- switch progress icons according to the mocks

Added steps progress status label and added correct icons.

---

config/setupTests.js
package-lock.json
package.json
src/helpers/order/order-helper.js
src/helpers/platform/platform-helper.js
src/helpers/portfolio/portfolio-helper.js
src/helpers/share/share-helper.js
src/helpers/shared/user-login.js
src/test/.eslintrc
src/test/redux/actions/approval-actions.test.js
src/test/redux/actions/order-actions.test.js
src/test/redux/actions/platform-actions.test.js
src/test/redux/actions/portfolio-actions.test.js
src/test/redux/actions/rbac-actions.test.js
src/test/smart-components/common/order-modal.test.js
src/test/smart-components/order/order-service-form-step-configuration.test.js
src/test/smart-components/order/orders.test.js
src/test/smart-components/platform/platform.test.js
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-pagination.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
src/test/smart-components/portfolio/portfolio.test.js

- migrate from fetch custom API calls to xhr (using axios)
- added request interceptor that checks user identity
- will redirect users once their jwt token expires
- currently is broken in chrome but fix is on its way
fixes #176

Migrate fetch to axios

---

src/presentational-components/order/order-notification.js
src/redux/actions/order-actions.js
src/test/presentational-components/order/__snapshots__/order-notification.test.js.snap
src/test/presentational-components/order/order-notification.test.js
src/test/redux/actions/order-actions.test.js
src/test/smart-components/order/order-service-form-step-configuration.test.js
src/test/smart-components/portfolio/portfolio.test.js

- updated order notification to match latest UX design
- added order ID to notifications
- updated the actions flow 
- updated tests after notification changes
- deleted leftover console log in portfolio test

Update order notification

---

src/App.js
src/App.scss
src/presentational-components/portfolio/portfolio-order-toolbar.js
src/presentational-components/shared/button-with-spinner.js
src/redux/reducers/order-reducer.js
src/smart-components/portfolio/add-products-to-portfolio/index.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/smart-components/common/order-modal.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js

- added button with spinner while ordering or adding items to portfolio
- this will be displayed if async request is in progress
used components from: https://redhat.invisionapp.com/share/6NPCR8DYP7F#/screens/360791839_UC4-E_Spinner_In_Button

Added button with spinner.

---

src/test/utilities/loading-state-middleware.test.js
src/test/utilities/store.test.js

- tests for redux store creation
- tests for loading state middleware

Utilities tests

---

src/smart-components/order/order-item.js
src/test/smart-components/order/__snapshots__/orders.test.js.snap
src/test/smart-components/order/orders.test.js

Open the 'Manage product' link in a new tab
Solves https://projects.engineering.redhat.com/browse/SSP-383

Open the 'Manage product' link in a new tab

---

package-lock.json
package.json
src/App.js
src/redux/actions/portfolio-actions.js

- adds react-intl context to App (https://github.com/formatjs/react-intl)
- we can now use proper pluralization in messages
- also it prepares  the app for the i18n

Added react intl provider

---

src/App.scss
src/presentational-components/portfolio/porfolio-card.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/utilities/store.test.js

- fixed invalid DOM nesting in portfolio card
- whole component was wrapped in Link and the header has dropdown with links
- it was causing invalid DOM nesting console error
- moved the portfolio card link only to card body.

Fix invalid DOM nesting in portfolio card.

---

src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/shared/card-common.js
src/presentational-components/shared/loader-placeholders.js
src/smart-components/platform/platform.js

- removes couple of console errors from browser

Removed console errors from browser.

---

src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js

Fixed the portfolio parameter for AddProductsToPortfolio render - this fixes an error on Add Products, a the portfolio is undefined.
Also fixes the spelling for the PortfolioItems component.

Fixed the portfolio parameter for AddProductsToPortfolio render

---

package-lock.json
package.json
src/utilities/store.js

- fixed runtime error when you get 403 response from catalog
- caused by wrong notification description key

Fix 403 response for portfolios.

---

src/helpers/order/order-helper.js
src/smart-components/order/order-service-form-step-configuration.js
src/test/smart-components/order/order-service-form-step-configuration.test.js

- removed provider control parameters from ordering modal

Removed provider control parameters from ordering.

---

src/App.scss
src/presentational-components/shared/button-with-spinner.js
src/smart-components/portfolio/portfolio.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap

- fixed loading flag in portfolio items component
- fixed misalignment on button with spinner

Fixed portfolio items loading flag.

---

src/forms/portfolio-share-form.schema.js
src/presentational-components/shared/loader-placeholders.js
src/smart-components/portfolio/share-portfolio-modal.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js

- adjusted share portfolio loader

Fixed share portfolio loader.

---

package-lock.json
package.json

Updates axios packages that was causing security vulnerabilities. (npm audit)

Updated axios to fix security vulnerabilities.

---

package-lock.json
package.json

- forms now support data types: http://data-driven-forms.surge.sh/renderer/data-types
- tower orders should work after https://github.com/ManageIQ/topological_inventory-ansible_tower/pull/17 is merged

Updated DDF to support data-types.

---

src/presentational-components/shared/loader-placeholders.js
src/smart-components/order/orders.js
src/test/smart-components/order/__snapshots__/orders.test.js.snap
src/test/smart-components/order/orders.test.js
src/toolbar/schemas/orders-toolbar.schema.js

- added open and closed orders tab

Added open and closed orders tabs

---

src/smart-components/order/order-item.js

- replaced `ordered_at` attribute with `created_at` date for the Ordered title in order

Replaced ordered at with created at date for orders.

---

src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/portfolio/portfolio-card-header.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/portfolio-card-header.test.js

Fixes missing link on portfolio card title.

Fix portfolio card link.

---

package-lock.json
package.json
src/forms/portfolio-form.schema.js
src/helpers/approval/approval-helper.js
src/presentational-components/shared/pf4-select-wrapper.js
src/smart-components/portfolio/add-portfolio-modal.js
src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js

- added debounced async filter for add/edit portfolio workflow selection

Added select with asynchronous filtering.

---

src/redux/actions/order-actions.js
src/smart-components/order/create-order-row.js
src/test/redux/actions/order-actions.test.js

- Added canceled orders to past orders
- Added correct icon to canceled state

Added canceled order to closed orders

---

src/smart-components/platform/platforms.js

- fixed outdated link to sources app

Fixed platforms empty state link to sources.

---

src/smart-components/order/order-detail-table.js
src/smart-components/order/order-messages-modal.js
src/smart-components/order/orders-list.js
src/smart-components/order/orders.js

fixes: https://github.com/ManageIQ/catalog-ui/pull/252#issuecomment-525817068
Added correct close url to progress messages modal.

Fixed wrong redirect when closing order progress messages.

---

src/forms/edit-portfolio-item-form.schema.js

Adds attribute validation based on: https://github.com/ManageIQ/catalog-api/pull/383

Added required validator to portfolio item display_name.

---

config/spandx.config.js
package-lock.json
package.json
src/test/utilities/store.test.js

- updated version of DDF to latest
- adds plain-text component
- fixed static aset serving in spandx config for development
- updated tests which were failing because of updated dependencies
This should be merged before https://github.com/ManageIQ/catalog-api/pull/408 to avoid temporary Ui fails. This does not introduce any changes to current UI.
cc @eclarizio

Update ddf 1.17.0

---

src/App.scss
src/helpers/portfolio/portfolio-helper.js
src/helpers/shared/user-login.js
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js

- added image uploader for portfolio item
- only works on first upload (when portfolio item does not have image)
- edit endpoint does not work yet
cc @lindgrenj6

Portfolio item icon upload

---

src/utilities/store.js

- added new key to notification middleware config to prevent UI crashes.

Added new error key to notifications config.

---

src/App.scss
src/presentational-components/shared/conditional-link.js
src/presentational-components/shared/service-offering-body.js
src/smart-components/portfolio/portfolio-item.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
src/test/presentational-components/shared/conditional-link.test.js
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap

- make only card title link
- added word break for long words in card description
- removed some console log leftover

Portfolio card title click

---

package-lock.json
package.json
src/helpers/order/order-helper.js
src/helpers/portfolio/portfolio-helper.js
src/helpers/shared/user-login.js
src/redux/actions/order-actions.js
src/smart-components/portfolio/add-portfolio-modal.js
src/test/redux/actions/order-actions.test.js
src/test/smart-components/portfolio/portfolio.test.js

- use proper param serializer to serialize URL query.
- continuation of: https://github.com/ManageIQ/catalog-ui/pull/259
- replacing hot fix with proper library
- remove unused methods
- switched to generated client method where possible

Audit of API calls

---

.eslintrc.yml
src/helpers/shared/helpers.js
src/smart-components/portfolio/share-portfolio-modal.js
src/utilities/constants.js

- turned of the camelcase eslint rule
- API uses snakecase and we cannot do anything about these warnings when we use variables from API responses.
- fixed some minor eslint warnings

Eslint warnings

---

config/spandx.config.js

- configure spadnx config for ansible namespace

Adjust spandx for ansible namespace

---

config/webpack.common.js

Remove hybrid from webpack.common.js

---

src/smart-components/platform/platforms.js

Updated sources link to ansible

Updated sources link to ansible

---

src/smart-components/order/create-order-row.js
src/smart-components/order/order-item.js

Jira ticket: https://projects.engineering.redhat.com/browse/SSP-806
UI part of: https://github.com/ManageIQ/catalog-api/pull/418#event-2692654735

Use request_completed_at for orders.

---

package-lock.json
package.json
src/helpers/portfolio/portfolio-helper.js
src/presentational-components/shared/filter-toolbar-item.js
src/smart-components/common/async-pagination.js
src/smart-components/portfolio/portfolios.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/common/__snapshots__/order-modal.test.js.snap
src/test/smart-components/order/__snapshots__/order-detail-table.test.js.snap
src/test/smart-components/order/__snapshots__/order-service-form-step-configuration.test.js.snap
src/test/smart-components/order/__snapshots__/orders.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
src/test/smart-components/portfolio/__snapshots__/remove-portfolio-modal.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
src/test/smart-components/portfolio/portfolios.test.js
src/test/smart-components/portfolio/remove-portfolio-modal.test.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js
src/toolbar/schemas/portfolios-toolbar.schema.js

- Added async filtering by name for portfolios
- Portfolios component is now function using hooks
- updated react-router-dom to be able to use router hooks
- fixed default count value for async pagination to 0
- no longer shows 0 - 50 before the first API request is finished. Now its 0 - 0

Add async filtering to portfolios

---

src/toolbar/schemas/portfolio-toolbar.schema.js

Move the edit portfolio button top the kebab menu
https://projects.engineering.redhat.com/browse/SSP-814
Before:
After:

Move the edit portfolio button top the kebab menu

---

src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js

I've found some left over console log statement from previous work.

Removed console log from test file.

---

src/App.scss
src/forms/form-fields/shage-group-edit.js
src/forms/form-fields/share-group-select.js
src/forms/portfolio-share-form.schema.js
src/presentational-components/shared/loader-placeholders.js
src/smart-components/common/form-renderer.js

- update share portfolio look
https://projects.engineering.redhat.com/browse/SSP-350
https://marvelapp.com/625jh26/screen/59029719

Updated share portfolio modal to look more like mocks.

---

src/constants/nullable-attributes.js
src/forms/edit-portfolio-item-form.schema.js
src/forms/portfolio-form.schema.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
src/test/forms/portfolio-form.schema.test.js
src/test/smart-components/portfolio/add-portfolio-modal.test.js

part of #289 
Mentioned PR has now conflicts with the taggin PR @lgalis is working. I want to move forward with that after #289 because its not that important.
However we need to fix the `workflow_ref` attribute which was removed in https://github.com/ManageIQ/catalog-api/pull/463 because its breaking UI.

Removed workflow ref rom portfolio and portfolio item

---

src/App.js
src/Routes.js
src/forms/edit-portfolio-item-form.schema.js
src/helpers/portfolio/portfolio-helper.js
src/helpers/shared/helpers.js
src/redux/action-types.js
src/redux/actions/portfolio-actions.js
src/redux/reducers/open-api-reducer.js
src/test/__mocks__/open-api-mock.js
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
src/test/utilities/store.test.js
src/utilities/store.js

Included commits from the following PRs:
https://github.com/ManageIQ/catalog-ui/pull/281  `Removed isRequired from product description`
https://github.com/ManageIQ/catalog-ui/pull/285 `Fixed unpermitted parameters in edit portfolio item payload.`
https://github.com/ManageIQ/catalog-ui/pull/286 `Sanitize patch requests based on openApi schema`
Resolves portfolio editing issues in QA and Prod envs.

[Stable] PortfolioItem edit hotfix

---

src/presentational-components/portfolio/porfolio-card.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/toolbar/schemas/portfolio-toolbar.schema.js

- pf update did cause some visual issues with dropdown buttons. This Pr fixes it

Fixed dropdown styling after PF update

---

package-lock.json
src/helpers/platform/platform-helper.js
src/redux/actions/platform-actions.js
src/smart-components/platform/platform-templates.js
src/smart-components/platform/platform.js
src/smart-components/portfolio/add-products-to-portfolio/index.js
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/platform/__snapshots__/platform-templates.test.js.snap
src/test/smart-components/platform/__snapshots__/platform.test.js.snap
src/test/smart-components/platform/platform-templates.test.js
src/test/smart-components/platform/platform.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

Convert the platform template page to use hooks.  Update filtering and specs.
https://projects.engineering.redhat.com/browse/SSP-907

Convert platform templates to use hooks.

---

src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-table-helpers.js
src/test/smart-components/platform/platform-inventories.test.js
src/utilities/constants.js

Added the kebab menu with the 'Edit approval for an inventory.
https://projects.engineering.redhat.com/browse/SSP-895

Added the kebab menu with the 'Edit approval for an inventory 

---

src/helpers/portfolio/portfolio-helper.js
src/presentational-components/shared/breadcrubms.js
src/presentational-components/shared/conditional-link.js
src/presentational-components/shared/service-offering-body.js
src/redux/action-types.js
src/redux/actions/portfolio-actions.js
src/redux/reducers/portfolio-reducer.js
src/smart-components/common/edit-approval-workflow.js
src/smart-components/common/order-modal.js
src/smart-components/order/order-detail/order-detail-menu.js
src/smart-components/order/order-detail/order-detail.js
src/smart-components/order/order-service-form-step-configuration.js
src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/portfolio/portfolio-item.js
src/smart-components/portfolio/portfolio-items.js
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
src/utilities/use-query.js

- use query based routing in portfolio item detail pages
- more efficient and direct way to get specific data from API

Portfolio item routing

---

src/smart-components/order/order-detail/order-detail-information.js
src/smart-components/order/order-detail/order-detail.js
src/smart-components/order/order-detail/order-details.js

- use correct date for order detail
- removed job name (we don't have it)
- added missing test to relative dates in order detail header

Fixed order detail invalid dates and removed job name.

---

src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap

QE requested some identifiers on these elements.
Ids match the ids from edit form.

Added ids to portfolio item detail paragraphs.

---

src/redux/actions/portfolio-actions.js

https://projects.engineering.redhat.com/browse/SSP-964
Before:
After:

Fix for the copy portfolio alert message

---

README.md

There are other references that need to be changed, but doing this separate as it does not effect dependencies and restores the travis link.

Update readme.md to use RedHatInsights org

---

src/presentational-components/shared/top-toolbar.js
src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
src/toolbar/toolbar-mapper.js

Fixed left spacing for toolbars

---

package-lock.json
package.json
src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap

Update react-core version and snapshot  Replaces https://github.com/RedHatInsights/catalog-ui/pull/327

Update react core version

---

src/presentational-components/portfolio/porfolio-card.js
src/smart-components/platform/platform-inventories.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/smart-components/platform/platform-inventories.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/toolbar/schemas/portfolio-toolbar.schema.js

Change the edit approval menu item to 'Set approval' and removed the separator:

Update edit approval menu item

---

package-lock.json
package.json
src/forms/form-fields/share-group-select.js
src/forms/portfolio-share-form.schema.js
src/helpers/rbac/rbac-helper.js
src/smart-components/portfolio/share-portfolio-modal.js

Add async select to the share portfolio modal

Add async select to the share portfolio modal

---

package-lock.json
package.json
src/presentational-components/shared/pf4-select-wrapper.js

Update ddf to fix select portaling.

---

src/test/smart-components/portfolio/share-portfolio-modal.test.js

Temp. fix - skip one of the tests - each run separately succeeds.

Skip mount test

---

package-lock.json
package.json
src/helpers/shared/user-login.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/survey-editing/survey-editor.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap

- added survey editor to portfolio items
- editing works
- ~~turn off adding and changing order of fields (will be done in DDF)~~ done
- turn of removing fields
- validation editing (Will be done in DFF)
- visual design (Susan is working on that)

Added basic survey editing.

---

src/presentational-components/shared/breadcrubms.js
src/presentational-components/shared/top-toolbar.js
src/smart-components/common/async-pagination.js
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
src/test/smart-components/order/__snapshots__/orders.test.js.snap
src/toolbar/schemas/orders-toolbar.schema.js
src/toolbar/schemas/portfolios-toolbar.schema.js
src/toolbar/schemas/products-toolbar.schema.js
src/toolbar/toolbar-mapper.js

- added correct spacing values in the toolbar components. Based off https://docs.google.com/spreadsheets/d/1E6VamH5K7tpxVO9zTp69M2NiIq6xqg7cB0w2rFmU8fo/edit#gid=0
- fixes are applied to every page with toolbar
(its is difficult to spot but the difference is there)

Fixed up toolbar spacing

---

src/app-context.js
src/entry-dev.js
src/entry.js
src/presentational-components/shared/content-gallery-empty-state.js
src/smart-components/order/orders-list.js
src/smart-components/platform/platform-templates.js
src/smart-components/portfolio/portfolio-empty-state.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/products/products.js

- no major visuals just changing words and spacing here and there
Based on https://docs.google.com/spreadsheets/d/1E6VamH5K7tpxVO9zTp69M2NiIq6xqg7cB0w2rFmU8fo/edit#gid=0 feedback

Empty states

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/survey-editing/survey-editor.js

- added PF styled controls to suver editor overlay

Added more controls to suver editor overlay

---

src/smart-components/order/order-detail/order-detail-menu.js
src/smart-components/order/order-detail/order-detail.js
src/smart-components/order/order-detail/order-lifecycle.js

- Enabled life cycle for completed orders
- Only contains the manage products links
- fixed spacing for order toolbar

Add manage product link

---

package-lock.json
package.json

- update survey editor package to be able to edit field validation

Update survey editor to allow validation editing.

---

src/smart-components/common/order-modal.js
src/test/smart-components/common/order-modal.test.js

ui part of https://github.com/RedHatInsights/catalog-api/pull/523
DEPENDANT ON  - https://github.com/RedHatInsights/catalog-api/pull/523

Removed service_plans_ref from order payload.

---

src/helpers/portfolio/portfolio-helper.js
src/redux/reducers/portfolio-reducer.js
src/smart-components/common/async-pagination.js
src/smart-components/order/orders-list.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
src/test/redux/actions/portfolio-actions.test.js
src/test/redux/reducers/portfolio-reducer.test.js
src/test/smart-components/portfolio/__snapshots__/portfolio.test.js.snap
src/test/smart-components/portfolio/portfolio.test.js
src/toolbar/helpers.js
src/toolbar/schemas/portfolio-toolbar.schema.js
src/toolbar/schemas/portfolios-toolbar.schema.js
src/toolbar/schemas/products-toolbar.schema.js
src/toolbar/toolbar-renderer.js

based on https://docs.google.com/spreadsheets/d/1E6VamH5K7tpxVO9zTp69M2NiIq6xqg7cB0w2rFmU8fo/edit#gid=0
- certain components are supposed to be hidden when no items in a list are found
- pagination
- action elements which manipulate items in the list (buttons, dropdowns etc)
- refactored portfolio component to use hooks

Hiding toolbar components when no data in list

---

src/presentational-components/order/order-notification.js
src/redux/actions/portfolio-actions.js
src/test/smart-components/portfolio/portfolio.test.js

Removed some unnecessary elements to improve QE selectors. No visual changes.

Removed parent text elements in notifications.

---

src/smart-components/platform/platforms.js

Again had to update the settings link to sources.

Fixed empty state sources link.

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js

fixes: https://projects.engineering.redhat.com/browse/SSP-990
- added `portfolioItemId` change as a trigger for portfolio item detail data fetching

Fixed redirect after portfolio item copy.

---

package-lock.json
package.json
src/App.scss
src/presentational-components/portfolio/portfolio-card.scss
src/presentational-components/shared/card-common.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap
src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/portfolio/__snapshots__/remove-portfolio-modal.test.js.snap
src/test/smart-components/portfolio/remove-portfolio-modal.test.js

fixed card word break

---

src/App.js
src/App.scss
src/redux/reducers/platform-reducer.js
src/smart-components/common/async-pagination.js
src/smart-components/order/orders-list.js
src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-templates.js
src/smart-components/portfolio/add-products-to-portfolio/index.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolios.js
src/smart-components/products/products.js
src/toolbar/schemas/add-products-toolbar.schema.js
src/toolbar/schemas/platforms-toolbar.schema.js
src/toolbar/schemas/portfolio-toolbar.schema.js
src/toolbar/schemas/portfolios-toolbar.schema.js
src/toolbar/schemas/products-toolbar.schema.js

- added bottom pagination component to content with top pagination
- changed the top paginations to use a compact variant
- Fixed wrong API params for template/inventories pagination
- Replaced Red hat insights frontend components pagination with existing Asyncpagination component in templates and inventories
- Fixed missing spacing on the templates/inventories toolbar below tabs

Compact navigation

---

src/smart-components/common/edit-approval-workflow.js
src/smart-components/platform/platform-inventories.js
src/test/smart-components/platform/platform-inventories.test.js
src/utilities/constants.js

Update the app_name used in set approval to match the object type.
Fixed the id used when tagging an inventory.

Update inventory object and app name

---

package.json
src/App.scss
src/forms/portfolio-form.schema.js
src/helpers/shared/helpers.js
src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/shared/content-list.js
src/presentational-components/shared/top-toolbar.js
src/redux/actions/portfolio-actions.js
src/smart-components/common/form-renderer.js
src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-table-helpers.js
src/smart-components/platform/platform-templates.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/remove-portfolio-modal.js
src/smart-components/products/products.js
src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/remove-portfolio-modal.test.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js
src/toolbar/schemas/platforms-toolbar.schema.js
src/toolbar/schemas/portfolio-toolbar.schema.js
src/toolbar/schemas/portfolios-toolbar.schema.js
src/toolbar/schemas/products-toolbar.schema.js

- updated labels and placeholders and spacings across the app
- added modal context to form renderer to enable different styling

Fit and finish part 2

---

src/presentational-components/shared/bottom-pagination-container.js
src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-templates.js
src/smart-components/platform/platforms.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolios.js

- top and bottom padding in bottom pagination were changed to pf-md modifier to match ansible automation spacing.
- removed section component around Platforms page to force pagination to the bottom of the page.

Adjusted bottom pagination spacing.

---

src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolios.js

I've missed the portfolios filter placeholder in the last fit n finish update.

Changed portfolios filter placeholder.

---

src/helpers/platform/platform-helper.js
src/redux/action-types.js
src/redux/actions/platform-actions.js
src/redux/reducers/platform-reducer.js
src/smart-components/platform/platform-templates.js
src/smart-components/platform/platforms.js
src/smart-components/platform/service-offering/service-offering-detail.js
src/test/redux/actions/platform-actions.test.js
src/test/redux/reducers/platform-reducer.test.js
src/test/smart-components/platform/service-offering/service-offering-detail.test.js

- added detail page for source service offering
- this was brought up during the fit-n-finish
- no design for it just yet, but it should be pretty similar to the portfolio item detail

Platform service offering

---

src/smart-components/survey-editing/survey-editor.js

thanks to https://github.com/RedHatInsights/catalog-api/pull/536/files it is now possible to tell if we should create or patch existing survey

Survey editor patch request

---

src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js

- use async select for portfolio list in copy portfolio modal

Changed copy portfolio select to async select with filter.

---

src/presentational-components/shared/top-toolbar.js

Adresses: https://github.com/RedHatInsights/catalog-ui/pull/376#issuecomment-574802337

Change toolbar description variant from small to p.

---

package-lock.json
package.json
src/smart-components/survey-editing/survey-editor.js

- enable subset mode for survey editing
- this disables/restricts some editing features
- for instance, if a field is required in base schema, it cannot be changed
- if a field has a validation of minimum value set to 5, you can set it to 6 but not to 4
The next thing on the agenda is design. That might take much longer.

Enable subset mode for survey editing.

---

package-lock.json
package.json

Most work has been done in https://github.com/data-driven-forms/form-builder

Updated survey editor with PF4 visuals.

---

src/presentational-components/shared/breadcrubms.js
src/presentational-components/shared/top-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js

- will notify user if the image upload has failed and shows server error message
waiting for https://github.com/RedHatInsights/catalog-api/pull/547 to be merged, to check the size validation and error response

Added error handling for image upload.

---

src/App.scss
src/helpers/shared/helpers.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-breadcrumbs.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/survey-editing/survey-editor.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js

Waiting for #373 
I have realized that the routing and breadcrumbs must be re-worked. I'll be focusing on that for a while. It has become a massive technical debt.

Move survey editor from portal to standard page page

---

package-lock.json
package.json

- updated survey editor to be able to edit the initial value
**Form state preview is going to be later feature**

Add initial value to survey editor.

---

package-lock.json
package.json
src/forms/edit-workflow_form.schema.js
src/helpers/approval/approval-helper.js
src/redux/action-types/approval-action-types.js
src/redux/actions/approval-actions.js
src/smart-components/common/edit-approval-workflow.js
src/test/smart-components/common/edit-approval-workflow.test.js

Set multiple approval processes (workflows) for resources:
Notifications combined into one:

Set multiple approval processes (workflows) for resources

---

src/redux/reducers/portfolio-reducer.js

ticket: https://projects.engineering.redhat.com/browse/SSP-1160
- added a missing handler for restoring portfolio item after failed update

Fix missing handler for restore portfolio item prev state.

---

package-lock.json
package.json
src/test/smart-components/common/order-modal.test.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js

- form state handling to the form preview (not validations right now)
- restore select options from base schema

Added form state to survey editing and restoreable options.

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/survey-editing/survey-editor.js

Add notifications to survey editor events.

---

package-lock.json
package.json

There was a bug in data driven forms with initializing multi select value in async mode.
Code changesl can be found in this PR: https://github.com/data-driven-forms/react-forms/pull/298

Fixed missing initial value in edit workflow modal.

---

package-lock.json
package.json
src/helpers/portfolio/portfolio-helper.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

Replace the 2 endpoint calls for creating a portfolio item and adding it to a portfolio with one endpoint having a new, portfolioId parameter

Update the endpoint for creating a new portfolio item

---

src/smart-components/platform/platforms.js

Small update for the platform page empty message
https://projects.engineering.redhat.com/browse/SSP-878

Small update for the platform page empty message

---

package-lock.json
package.json
src/App.scss
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/survey-editing/survey-editor.js

- add hide field option
- add validation to disabled, read-only and hidden validation if the field is required
- field must have an initial value if is required and have one of these properties
- small fix on the icon upload styling
- the div was full width and licking anywhere on the toolbar triggered the upload dialog to open
(the title in survey editor is fixed)

Update survey editor with validation and hide features.

---

src/redux/actions/platform-actions.js
src/smart-components/order/orders-list.js
src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-templates.js
src/test/smart-components/platform/platform-templates.test.js

Fixed the filtering when there are no results for the entered value.
Fixed debounce so filtering does not happen on every key.
Add  period to the orders empty description message.
https://projects.engineering.redhat.com/browse/SSP-1155

Update platform inventory and template filtering

---

src/presentational-components/shared/content-gallery-empty-state.js
src/smart-components/products/products.js

https://projects.engineering.redhat.com/browse/SSP-879

Update empty page primary action buttons to primary variant

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js

https://projects.engineering.redhat.com/browse/SSP-1179
Update the parameter to source from platform item:
Before:
After:

Updated source name for product detail page

---

src/redux/actions/order-actions.js

https://projects.engineering.redhat.com/browse/SSP-1206
Check for the approval request presence before trying to set its state

Fixed error on Cancel order before approval

---

src/smart-components/order/order-detail/order-details.js

Change label from Request ID to Order ID to match the value.

---

src/presentational-components/platform/platform-item.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap

- fix card header layout on platform item card.

Fix card header layout on platform item card.

---

src/presentational-components/shared/filter-select.js
src/smart-components/portfolio/add-products-to-portfolio/index.js
src/smart-components/portfolio/portfolio.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

- no visual changes
- use redux hooks instead of connect
- fixed some console error about invalid/missing props

Refactor add products to portfolio to use redux hooks.

---

package-lock.json
package.json

- update survey editor to a new version
- has error indicators
- various performance increases

Update survey editor with error indicators.

---

src/smart-components/portfolio/share-portfolio-modal.js

- added missing dispatch wrapper to share portfolio call in order to trigger redux action creator
(styling is fixed in https://github.com/RedHatInsights/catalog-ui/pull/418)

Fixed missing dispatch in share portfolio.

---

src/smart-components/order/order-detail/order-detail-menu.js
src/smart-components/order/order-detail/order-detail.js

- disabled links in the order detail nav can no longer be clicked or focused

Fixed clickable disabled links in order detail.

---

package-lock.json
src/smart-components/order/order-detail/order-detail-menu.js
src/smart-components/order/order-detail/order-detail.js

- removed provision link from order detail tabs

Removed provision link from order tabs.

---

src/smart-components/order/order-detail/order-lifecycle.js

Can't show you screenshots because the RBAC is dead UI does not load any data.

Added external link icon to manage products link.

---

package-lock.json
src/helpers/portfolio/portfolio-helper.js
src/presentational-components/shared/service-offering-body.js
src/smart-components/products/products.js
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/products/products.test.js

- add portfolio name to the product card
What about portfolio items without any portfolio? Currently, it does not display the portfolio name and there is also no link since we don't have enough data to show the portfolio item detail. Should we filter out orphaned portfolio items?

Add portfolio name to product

---

package-lock.json
src/helpers/order/order-helper.js
src/redux/actions/order-actions.js
src/smart-components/order/order-item.js
src/smart-components/order/orders-list.js

- Enabled multi-filter for orders
- Added memoize around order items to increase performance

Add multi filter for orders.

---

package-lock.json
package.json
src/smart-components/survey-editing/survey-editor.js

- disable options value editing (https://github.com/data-driven-forms/form-builder/pull/11)
- removed input type from text field config
- use `imported` instead of the `modified` flag on surveys

Survey editor: restrict options value and input type.

---

package-lock.json
package.json
src/global-styles.js
src/presentational-components/shared/button-with-spinner.js
src/presentational-components/styled-components/level.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/survey-editing/survey-editor.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap

- added button to modified surveys to sync with topology (removes all changes made by user and uses base survey)
- fixed some console errors tied to incorrect prop types

Enable survey reset

---

src/presentational-components/shared/button-with-spinner.js
src/presentational-components/shared/loader-placeholders.js
src/presentational-components/styled-components/spinner-wrapper.js
src/smart-components/common/order-modal.js
src/smart-components/order/order-detail/order-detail.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/survey-editing/survey-editor.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap

Spinner looks like this: https://www.patternfly.org/v4/documentation/react/components/spinner

Replace frontend components spinner with PF spinner.

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js

- splits survey editor page to separate chunk, js will be loaded only when accessing the page
- detaches around 400KB from portfolio vendor chunk

Split survey editor from vendor bundle

---

src/App.js
src/Routes.js
src/routing/catalog-route.js
src/smart-components/error-pages/common-api-error.js
src/user-context.js

https://projects.engineering.redhat.com/browse/SSP-1317
- created wrapper around react route that can prevent a user from accessing sections of app based on chrome user permissions

Added routes permissions.

---

src/helpers/order/order-helper.js
src/presentational-components/styled-components/unavailable-alert-container.js
src/redux/reducers/order-reducer.js
src/smart-components/order/order-detail/order-detail.js
src/test/smart-components/order/orders.test.js

https://projects.engineering.redhat.com/browse/SSP-1311
- order detail will no longer redirect the user if order external resource fails to load
- PF alert is displayed with a warning that specific resource is not available

Add alert if order resource fails to load.

---

src/helpers/portfolio/portfolio-helper.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js

https://projects.engineering.redhat.com/browse/SSP-1302
- when the portfolio item source is no longer available, show a warning alert and disable the order button

Handle source 404 in portfolio item detail.

---

config/setupTests.js
src/helpers/shared/helpers.js
src/presentational-components/shared/content-gallery-empty-state.js
src/routing/catalog-route.js
src/smart-components/portfolio/portfolios.js
src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolios.test.js
src/toolbar/schemas/portfolios-toolbar.schema.js

Display the Create portfolio button/menu item based on permissions:

Display Create portfolio button based on permissions

---

package-lock.json
package.json
src/smart-components/survey-editing/survey-editor.js

addresses: https://projects.engineering.redhat.com/browse/SSP-1338
- the preview should more resemble PF4
- minor bug fixes
- improved layout modification
- fixes an issue with wrong data type on initial values

Update version of survey editor.

---

src/redux/actions/portfolio-actions.js

jira: https://projects.engineering.redhat.com/browse/SSP-1349

Use product instead of portfolio item in portfolio item notification.

---

package-lock.json
package.json

jira: https://projects.engineering.redhat.com/browse/SSP-1337

Update frontend notifications package

---

src/helpers/portfolio/portfolio-helper.js
src/redux/actions/portfolio-actions.js
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/portfolio/remove-portfolio-modal.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1355
- added undo link to notification after user deletes portfolio

Added undo delete portfolio feature.

---

package-lock.json
src/helpers/portfolio/portfolio-helper.js

jira: https://projects.engineering.redhat.com/browse/SSP-1315
- added check for the linked portfolio and products before iterating over them

Add check before linking product to portfolio.

---

package-lock.json
package.json
src/forms/portfolio-share-form.schema.js
src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/portfolio/portfolio-card-header.js
src/redux/reducers/portfolio-reducer.js
src/routing/catalog-route.js
src/smart-components/error-pages/error-redirects.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js
src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/remove-portfolio-modal.js
src/smart-components/portfolio/share-portfolio-modal.js
src/test/forms/portfolio-share.schema.test.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/portfolio-card.test.js
src/test/redux/reducers/portfolio-reducer.test.js
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/portfolio.test.js
src/test/smart-components/portfolio/portfolios.test.js
src/test/smart-components/portfolio/remove-portfolio-modal.test.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js
src/test/utilities/portfolio-toolbar.schema.test.js
src/toolbar/schemas/portfolio-toolbar.schema.js
src/toolbar/toolbar-renderer.js
src/utilities/constants.js

jira: https://projects.engineering.redhat.com/browse/SSP-1371
- switch to API version 1.1
- hide portfolio actions behind portfolio user_capabilities
- hide routes behind portfolio user_capabilities
- update babel to enable optional chaining

Portfolio user capabilities

---

config/setupTests.js
src/App.js
src/smart-components/platform/platforms.js
src/test/smart-components/platform/platforms.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1377

Add different platform empty state message for non org admin.

---

src/entry.js
src/utilities/store.js

I don't think that it's necessary for users to see redux debug messages in the console.

Remove redux logger from production store.

---

src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1386

Apply user capabilities on survey editor and icon upload.

---

src/smart-components/order/orders-list.js

https://projects.engineering.redhat.com/browse/SSP-1374

Add Canceled and Created as options for orders filtering

---

src/smart-components/portfolio/share-portfolio-modal.js

Fixed share portfolio from the card kebab menu.
https://projects.engineering.redhat.com/browse/SSP-1392

Fixed share portfolio from the card kebab menu

---

src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platform-templates.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolios.js
src/smart-components/products/products.js
src/toolbar/schemas/platforms-toolbar.schema.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1399

Remove ellipses from the filter placeholders

---

src/redux/reducers/portfolio-reducer.js
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1407
Successful  display of product after edit - user capabilities preserved:

Fix post edit product metadata

---

src/redux/actions/approval-actions.js

jira: https://projects.engineering.redhat.com/browse/SSP-1366

Replace workflow term by approval process in notification.

---

src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js

jira: https://projects.engineering.redhat.com/browse/SSP-1416
- select filter only returns portfolios with update capability set to true

Filter portfolio item targets based on capability

---

src/redux/actions/portfolio-actions.js
src/smart-components/portfolio/portfolio-empty-state.js
src/test/integration/portfolio-item-integration.test.js
src/toolbar/schemas/add-products-toolbar.schema.js

wait for #491 
- adds full DOM tests of a portfolio item in one sequence
- add
- update
- copy
- remove
- undo remove
- also fixes some minor technical debt like missing ids or props

Portfolio item integration

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js

jira: https://projects.engineering.redhat.com/browse/SSP-1406

Remove vendor name under the product icon.

---

src/smart-components/order/order-detail/order-detail-title.js
src/smart-components/order/order-item.js

jira: https://projects.engineering.redhat.com/browse/SSP-1398
Add `- order` to order title in the list and in the detail.

Add '- Order' to order title.

---

src/smart-components/portfolio/portfolio.js
src/utilities/use-is-mounted.js

jira: https://projects.engineering.redhat.com/browse/SSP-1422
- trigger portfolio items data fetch after a browser location change

Update portfolio items after location change.

---

src/test/smart-components/portfolio/portfolio.test.js
src/toolbar/schemas/portfolio-toolbar.schema.js

jira: https://projects.engineering.redhat.com/browse/SSP-1413

Replace portfolio item kebab with toolbar buttons.

---

src/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.js
src/smart-components/portfolio/add-products-to-portfolio/index.js

jira: https://projects.engineering.redhat.com/browse/SSP-1425
I have also used the filter icon instead of the search icon on the page first render.

Fixed empty space under add products bottom pagination.

---

src/constants/routes.js
src/smart-components/order/order-item.js

jira: https://projects.engineering.redhat.com/browse/SSP-1410

Change the order item link based on order state.

---

src/presentational-components/shared/filter-toolbar-item.js
src/smart-components/portfolio/add-products-to-portfolio/index.js
src/test/integration/portfolio-item-integration.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/toolbar/schemas/add-products-toolbar.schema.js

jira: https://projects.engineering.redhat.com/browse/SSP-1426
- hook the filtering and pagination to API

Use API pagination and filtering when adding products.

---

src/helpers/approval/approval-helper.js
src/helpers/portfolio/portfolio-helper.js
src/helpers/share/share-helper.js
src/presentational-components/portfolio/porfolio-card.js
src/redux/actions/portfolio-actions.js
src/smart-components/portfolio/portfolios.js
src/test/integration/portfolio-integration.test.js
src/test/integration/portfolio-item-integration.test.js
src/test/smart-components/common/edit-approval-workflow.test.js
src/test/smart-components/platform/platform-inventories.test.js

- if app mounts directly to the share modal, the app crashes because of missing portfolio object
- fixed by the conditional chain: https://github.com/RedHatInsights/catalog-ui/pull/514/files#diff-4a20391ff769b52e48f97b4b1e37e6d8R85
- there was an extra slash `/workflows/?` URL. Tested in browsers and it works without it

Portfolio approval share full APP testing

---

package-lock.json
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js

jira: https://projects.engineering.redhat.com/browse/SSP-1433

Fix button variants in edit product form.

---

src/redux/actions/approval-actions.js

jira: https://projects.engineering.redhat.com/browse/SSP-1441

Fix spelling of 'successfully' in the set approval alert

---

src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/share-portfolio-modal.js

Share portfolio modal - add description containing the portfolio name 
Fixes https://projects.engineering.redhat.com/browse/SSP-1373

Share portfolio modal - add description containing the portfolio name 

---

src/forms/form-fields/share-group-select.js
src/forms/portfolio-share-form.schema.js
src/smart-components/portfolio/share-portfolio-modal.js

Add share portfolio form validation
Fixes https://projects.engineering.redhat.com/browse/SSP-1320

Add share portfolio form validation

---

src/smart-components/order/order-detail/approval-request.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1400

Small update to the order's approval tab

---

src/smart-components/order/order-detail/order-detail-menu.js
src/smart-components/order/order-detail/order-lifecycle.js

jira: https://projects.engineering.redhat.com/browse/SSP-1460

Enable order lifecycle tab in ordered state.

---

src/presentational-components/portfolio/porfolio-card.js
src/presentational-components/styled-components/level.js
src/smart-components/platform/service-offering/service-offering-detail.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/test/integration/portfolio-integration.test.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/portfolio-card.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
src/test/utilities/portfolio-toolbar.schema.test.js
src/toolbar/schemas/portfolio-toolbar.schema.js

jira: https://projects.engineering.redhat.com/browse/SSP-1477
- fixed alignment on toolbar title in firefox
- added user capabilities for set approval
- empty dropdowns are not rendered

User capabilities for set approval

---

src/helpers/portfolio/portfolio-helper.js
src/redux/actions/portfolio-actions.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolios.js
src/test/integration/portfolio-integration.test.js
src/test/redux/actions/portfolio-actions.test.js

https://projects.engineering.redhat.com/browse/SSP-1408

Redirect to the newly created portfolio page

---

src/smart-components/order/order-detail/order-detail.js

Jira: https://projects.engineering.redhat.com/browse/SSP-1458
Old (mobile)
New (mobile)

Fix Order screen mobile layout margins

---

src/App.js
src/forms/portfolio-form.schema.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolios.js
src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/utilities/constants.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1482

Set max length for the portfolio name as specified in the openapi schema

---

src/smart-components/portfolio/share-portfolio-modal.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1484

Update submit button to 'Apply'

---

src/presentational-components/portfolio/porfolio-card.js
src/redux/actions/portfolio-actions.js
src/smart-components/common/catalog-link.js
src/smart-components/common/edit-approval-workflow.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/remove-portfolio-modal.js
src/smart-components/portfolio/share-portfolio-modal.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
src/test/redux/actions/portfolio-actions.test.js
src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/utilities/use-enhanced-history.js

jira: https://projects.engineering.redhat.com/browse/SSP-1486
- added the view state to add/update portfolio API call to preserver filtering and pagination settings

Fixed missing filtering options after adding/editing portfolio.

---

package-lock.json
src/redux/actions/portfolio-actions.js
src/redux/reducers/portfolio-reducer.js
src/router.js
src/smart-components/order/orders-list.js
src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
src/smart-components/portfolio/portfolio.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
src/test/smart-components/portfolio/portfolio.test.js
src/utilities/use-is-mounted.js

- removed some console errors
- missing metadata in tests
- wrong handling of isMounted in portfolio could potentially cause state updates on umnounted component
- removed isRequired from `value` in `ValueOnly` form component. The component can have empty value when loading initial data
- fixed missing `created_at` attribute after portfolio item update

Technical debt fixes

---

src/redux/reducers/portfolio-reducer.js
src/smart-components/portfolio/add-portfolio-modal.js

jira: https://projects.engineering.redhat.com/browse/SSP-1463
- there is was an API request concurrency issue after updating the portfolio from the detail page. The GET requests to update the portfolio (required to synchronize the portfolio when changing pathname) was triggered before the PATCH request finished and was overriding the updated data.
- now the GET request is triggered only after the PATCH requests finishes

Fix request sequence after portfolio update.

---

src/smart-components/order/order-detail/order-toolbar-actions.js

https://projects.engineering.redhat.com/browse/SSP-1525
Before:
After:

Remove 'Reorder' button until the feature is available

---

src/global-styles.js

Follow-up to: https://github.com/RedHatInsights/catalog-ui/pull/543

Add missing bracket

---

package-lock.json
package.json
src/utilities/constants.js

Update approval api path and client version

---

src/smart-components/order/order-detail/approval-request.js

Update the link to the approval request to the new parametrized route added here: https://github.com/RedHatInsights/approval-ui/pull/231
New route target:

Update approval link to the new parametrized route

---

src/presentational-components/styled-components/table.js
src/smart-components/order/order-item.js

qa-beta branch PR of https://github.com/RedHatInsights/catalog-ui/pull/580

[qa-beta] Adjust order screen image formatting

---

src/presentational-components/styled-components/table.js
src/smart-components/order/order-item.js

qa-stable branch PR of https://github.com/RedHatInsights/catalog-ui/pull/580

[qa-stable] Adjust order screen image formatting

---

src/smart-components/order/order-detail/approval-request.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1552
Update link to the approval request page based on new routes

Update link to the approval request page

---

src/smart-components/order/order-detail/approval-request.js

Prod-beta PR of https://github.com/RedHatInsights/catalog-ui/pull/591
> Fixes https://projects.engineering.redhat.com/browse/SSP-1552
> 
> Update link to the approval request page based on new routes

[Prod-beta] Update link to the approval request page

---

src/smart-components/order/order-detail/approval-request.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1546
Open approval request details from order in the same tab.

Open approval request details from order in the same tab

---

src/smart-components/order/order-detail/approval-request.js

Prod-beta PR of https://github.com/RedHatInsights/catalog-ui/pull/591
> Fixes https://projects.engineering.redhat.com/browse/SSP-1552
> 
> Update link to the approval request page based on new routes

[Prod-stable] Update link to the approval request page

---

src/global-styles.js

Reverts RedHatInsights/catalog-ui#596

Revert "eliminate unneeded scrollbar from modals"

---

src/global-styles.js
src/presentational-components/shared/filter-toolbar-item.js
src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap

Jira: https://projects.engineering.redhat.com/browse/SSP-1564
Before:
After:

adjust filters to handle long names

---

src/entry.js

I've missed the possible beta prefix when registering a service worker.

Add beta option to SW registration.

---

src/smart-components/order/order-detail/approval-request.js
src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
src/test/smart-components/common/edit-approval-workflow.test.js
src/test/smart-components/common/order-modal.test.js
src/test/smart-components/order/order-detail.test.js
src/test/smart-components/order/orders.test.js
src/test/smart-components/platform/platform-inventories.test.js
src/test/smart-components/platform/platform-templates.test.js
src/test/smart-components/platform/platforms.test.js
src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
src/test/smart-components/portfolio/add-portfolio-modal.test.js

wait for #603 
After the code splitting changes, I've notices some amount of technical debt in tests. This PR addresses it.

Tests audit

---

package-lock.json
src/presentational-components/shared/pf4-select-wrapper.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1594

Fixed the change parameter from the useFormApi hook

---

src/global-styles.js
src/smart-components/order/order-detail/order-detail.js

fixes spelling of "order-detail-content-container"

fix class name

---

src/smart-components/common/order-modal.js

jira: https://projects.engineering.redhat.com/browse/SSP-1651
- add a cancel button to order modal

Add cancel button to order modal.

---

src/toolbar/schemas/add-products-toolbar.schema.js

Fix for https://projects.engineering.redhat.com/browse/SSP-1615

Add isSearchable attribute to the platform filter select

---

src/smart-components/common/order-modal.js

This PR reorganizes the upper portion of the modal per UX review.
Follow-up: https://github.com/RedHatInsights/catalog-api/pull/778
jira: https://projects.engineering.redhat.com/browse/SSP-1647
Old
New

Update order modal styling

---

src/messages/orders.messages.js
src/messages/states.messages.js
src/smart-components/order/order-detail/order-detail-information.js
src/smart-components/order/order-detail/order-detail-title.js
src/smart-components/order/order-detail/order-detail.js
src/smart-components/order/order-detail/order-toolbar-actions.js
src/smart-components/order/order-item.js

jira: https://projects.engineering.redhat.com/browse/SSP-1672
cc @sbuenafe-rh @fionayhlin

Apply new design to the order header.

---

package-lock.json
package.json
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

(cherry picked from commit 7858bfa12209a0dc9eaf4f66d914a756073f2765)

[PROD-BETA] Update DDF to fix select menu glitches.

---

package-lock.json
package.json
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js

(cherry picked from commit 7858bfa12209a0dc9eaf4f66d914a756073f2765)

[STABLE]Update DDF to fix select menu glitches.

---

src/presentational-components/portfolio/porfolio-card.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap

jira: https://projects.engineering.redhat.com/browse/SSP-1421

Add portfolio item count to portfolio card

---

src/messages/portfolio.messages.js
src/presentational-components/portfolio/back-to-products.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js
src/smart-components/products/products.js
src/toolbar/schemas/portfolio-toolbar.schema.js

jira: https://projects.engineering.redhat.com/browse/SSP-1694

Added back button to products.

---

src/constants/routes.js
src/helpers/shared/breadcrumbs-creators.js
src/messages/portfolio.messages.js
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1684
- hide the left information panel in the edit product form
- allow image editing only inside the edit product page
- add breadcrumb partial for edit product page
- changed the title in the edit product page
cc @sbuenafe-rh @fionayhlin

Update portfolio item edit

---

src/forms/form-fields/share-group-edit.js
src/forms/form-fields/share-group-select.js
src/forms/portfolio-share-form.schema.js
src/global-styles.js
src/messages/portfolio.messages.js
src/messages/schemas.messages.js
src/presentational-components/styled-components/level.js
src/redux/actions/share-actions.js
src/smart-components/portfolio/share-portfolio-modal.js
src/test/forms/portfolio-share.schema.test.js
src/test/integration/portfolio-share-workflow.test.js
src/test/smart-components/portfolio/share-portfolio-modal.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1681
- the group list is now dynamic
- can add multiple groups at once
- user must use the `+` button to add the group
- new icon for group deletion
- submit button is disabled until the form is in `dirty` state

Share modal refactor

---

src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js

Add missing grow property to product toolbar

---

src/messages/portfolio.messages.js
src/smart-components/portfolio/remove-portfolio-modal.js

jira: https://projects.engineering.redhat.com/browse/SSP-1693

Update delete portfolio modal

---

package-lock.json
package.json
src/forms/form-fields/copy-name-display.js
src/messages/labels.messages.js
src/smart-components/common/form-renderer.js
src/smart-components/dialog-routes/portfolio-routes.js
src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
src/test/integration/portfolio-item-integration.test.js

jira:
- https://projects.engineering.redhat.com/browse/SSP-1714
- https://projects.engineering.redhat.com/browse/SSP-1716
- spacebar key event is normal used to close/open the select menu (aria accessibility standard)
- the input was propagating the event to the toggle root element which causes unwanted menu toggle
- the keyDown event is no longer propagated to its parents (DDF PR: https://github.com/data-driven-forms/react-forms/pull/660)
- The text component showing the next name causing form re-initialization which deletes the value from the select component
- the next name component is now directly connected to the form state and has its internal logic to get the next name instead

Fix copy select value

---

src/toolbar/schemas/portfolio-toolbar.schema.js

https://projects.engineering.redhat.com/browse/SSP-1689
**Before**
**After**
@Hyperkid123

Move edit button to first place in portfolio item dropdown

---

src/messages/portfolio.messages.js
src/redux/actions/portfolio-actions.js
src/smart-components/portfolio/add-portfolio-modal.js
src/test/redux/actions/portfolio-actions.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1686
- notification is translated
- the portfolio name is **bold**

Update add portfolio notification

---

src/smart-components/platform/service-offering/service-offering-detail.js

Relates to: https://github.com/RedHatInsights/catalog-ui/pull/685
Jira: https://projects.engineering.redhat.com/browse/SSP-1728
Old
New

Add missing "grow" property to service offering detail header

---

src/messages/portfolio.messages.js
src/redux/actions/portfolio-actions.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js
src/test/redux/actions/portfolio-actions.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1691

Update remove products notification message.

---

src/helpers/portfolio/share-portfolio-message.js
src/messages/portfolio.messages.js
src/smart-components/portfolio/share-portfolio-modal.js
src/test/helpers/porftolio/share-portfolio-message.test.js

https://projects.engineering.redhat.com/browse/SSP-1687
TODO:

Update share modal message

---

src/smart-components/common/edit-approval-workflow.js
src/smart-components/portfolio/add-portfolio-modal.js
src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js

Catalog part of https://projects.engineering.redhat.com/browse/SSP-1731
cc @Hyperkid123

Disable edit/add forms on pristine

---

package-lock.json
package.json
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/survey-editing/survey-editor.js

https://projects.engineering.redhat.com/browse/SSP-1683
TO DO
:no_entry_sign:  ~~Add survey variant~~ survey always exists
**Before**
**After**

Remove icon and change title in edit survey

---

src/forms/create-order-process.schema.js
src/messages/forms.messages.js
src/messages/order-processes.messages.js
src/smart-components/order-process/add-order-process-modal.js
src/smart-components/order-process/order-processes.js
src/test/smart-components/order-process/__snapshots__/add-order-process-modal.test.js.snap
src/test/smart-components/order-process/add-order-process-modal.test.js

+ add tests for add order process modal
+ small refactoring
@Hyperkid123

Add tests for add order process modal

---

src/redux/action-types.js
src/redux/actions/order-process-actions.js
src/smart-components/order-process/order-processes.js
src/test/smart-components/order-process/order-processes.test.js

Store filtering and pagination settings to order processes URL hash

Add persistent filtering to order processes

---

src/constants/routes.js
src/helpers/order-process/order-process-helper.js
src/messages/actions.messages.js
src/messages/order-processes.messages.js
src/presentational-components/shared/loader-placeholders.js
src/presentational-components/shared/table-toolbar-view.js
src/redux/action-types.js
src/redux/actions/order-process-actions.js
src/redux/reducers/order-process-reducer.js
src/smart-components/order-process/order-process-table-context.js
src/smart-components/order-process/order-process-table-helpers.js
src/smart-components/order-process/order-processes.js
src/smart-components/order-process/remove-order-process-modal.js
src/test/presentational-components/shared/table-toolbar-view.test.js
src/test/smart-components/order-process/__snapshots__/remove-order-process-modal.test.js.snap
src/test/smart-components/order-process/remove-order-process-modal.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/utilities/use-order-process.js

https://projects.engineering.redhat.com/browse/SSP-1712
Add remove order process modal
Order process list selectable.
More tests

Add Remove Order process(es) modal. Order process list selectable

---

src/constants/routes.js
src/helpers/order-process/order-process-helper.js
src/messages/order-processes.messages.js
src/redux/action-types.js
src/redux/actions/order-process-actions.js
src/smart-components/order-process/add-order-process-modal.js
src/smart-components/order-process/order-processes.js
src/smart-components/order-process/remove-order-process-modal.js
src/test/smart-components/order-process/__snapshots__/add-order-process-modal.test.js.snap
src/test/smart-components/order-process/add-order-process-modal.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1711
- added edit variant to the add order process modal
Note: The order process and portfolio forms have exactly the same user flow and functionality. I will create a follow-up PR later which will merge these two components into a single component.

Edit edit option to add order process modal.

---

src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/toolbars/portfolios-primary-toolbar.js
src/test/smart-components/portfolio/portfolios.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1734
- hide create portfolio button behind user permission check

Hide portfolio create button for users without permission.

---

src/messages/order-processes.messages.ts
src/smart-components/dialog-routes/portfolio-routes.js
src/smart-components/order-process/set-order-process-modal.js
src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1794
Before:
After:

Add the object name to the description in the order process modal

---

src/helpers/order/order-helper.ts

Fixes https://projects.engineering.redhat.com/browse/SSP-1808
Before:
After:

Updated graphql query to get the request and subrequests with their actions

---

src/presentational-components/portfolio/porfolio-card.tsx

jira: https://issues.redhat.com/browse/SSP-1810

Updated shared label color

---

package-lock.json
package.json

Fixes https://issues.redhat.com/browse/SSP-1838

Update workbox-webpack-plugin for security vulnerability fix

---

src/presentational-components/portfolio/porfolio-card.tsx
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap

https://issues.redhat.com/browse/SSP-1811
Before:
After:

Updated portfolio card layout

---

src/smart-components/portfolio/add-portfolio-modal.tsx

Remove the unused isLoading modal parameter.
Fixes https://issues.redhat.com/browse/SSP-1862
Before -  
After:

Fix the Add/Edit portfolio modal loading

---

package-lock.json
package.json
src/smart-components/dialog-routes/portfolio-routes.tsx

Fixed the removeQuery parameter value for the add portfolio modal
Fixes https://issues.redhat.com/browse/SSP-1866

Fixed Add Portfolio error

---

src/redux/reducers/portfolio-reducer.ts
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/test/integration/portfolio-item-integration.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js

Fixes https://issues.redhat.com/browse/SSP-1872 and https://issues.redhat.com/browse/SSP-1799
1. The Order button is displayed based on the orderable flag and source availability status
2. The kebab menu is hidden when the source is no longer available

Display the Order button based on the orderable metadata flag

---

src/smart-components/order-process/order-processes.js

Fixes https://issues.redhat.com/browse/SSP-1879

Fix for the order process list crash on loading

---

src/presentational-components/platform/platform-card.tsx
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/platform/platform-card.test.js

Use platform icon urls from the source types API in the platform cards.
Fixes https://issues.redhat.com/browse/SSP-1906
Before:
After:

Fixed icons used in the Platform cards

---

src/smart-components/survey-editing/survey-editor.js

https://issues.redhat.com/browse/SSP-1869
- add template property to Text, TextArea and PlainText components
- set the isDisabled flag to true if the isTemplate flag is changed to true
- set the placeholder to the initial value when isTemplate is set to true

Add template flag to Survey editor

---

src/smart-components/order-process/add-order-process-modal.tsx

Fixes https://issues.redhat.com/browse/SSP-1890

Fixed removing an order process' description

---

src/smart-components/common/order-modal.tsx
src/smart-components/survey-editing/survey-editor.js

Suppress validation for substitution fields in the order modal.

Suppress validation for substitution fields in the order modal

---

src/smart-components/survey-editing/survey-editor.js

Rename Template/isTemplate to Substitution/isSubstitution

---

package-lock.json
package.json
src/helpers/order/order-helper.ts
src/messages/orders.messages.ts
src/smart-components/order/order-detail/order-lifecycle.tsx

https://issues.redhat.com/browse/SSP-1873

Add order item artifacts to the lifecycle tab

---

src/messages/forms.messages.ts

as discussed in the UX
After:
Before
review

Update before/after labels for order process modal

---

src/smart-components/order/order-detail/order-provision.tsx
src/smart-components/order/order-status-mapper.tsx

FIxes https://issues.redhat.com/browse/SSP-1950

Order provision page styling changes

---

src/helpers/order-process/order-process-helper.ts
src/redux/actions/order-process-actions.ts
src/smart-components/order-process/order-processes.js
src/smart-components/order/order-detail/order-provision.tsx
src/types/common-types.d.ts

Fixes https://issues.redhat.com/browse/SSP-1923

Fix for order processes sorting

---

src/smart-components/order/order-detail/order-details.tsx

Fixes https://issues.redhat.com/browse/SSP-1899
Before:
After:

Fix order details parameters overflow 

---

src/smart-components/order/order-detail/order-detail-information.tsx

Fixes https://issues.redhat.com/browse/SSP-1949
Before:
After:

Update product font on the order details page

---

src/messages/states.messages.ts

Fixes https://issues.redhat.com/browse/SSP-1908

Handle unauthorized order detail error

---

src/presentational-components/platform/platform-card.tsx
src/presentational-components/platform/platform-item.tsx
src/presentational-components/portfolio/porfolio-card.tsx
src/presentational-components/shared/content-list.tsx
src/presentational-components/shared/table-toolbar-view.tsx
src/smart-components/order-process/order-process-table-helpers.js
src/smart-components/order-process/order-processes.js
src/smart-components/platform/platform-inventories.js
src/smart-components/platform/platforms.js
src/smart-components/portfolio/portfolio-item.js
src/smart-components/portfolio/portfolios.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap

Part 1 for https://issues.redhat.com/browse/SSP-1934
- tables and cards

Add OUIA id to tables and cards

---

src/forms/form-fields/share-group-edit.tsx
src/forms/form-fields/share-group-select.tsx
src/presentational-components/portfolio/back-to-products.tsx
src/smart-components/order-process/order-processes.js
src/smart-components/order-process/remove-order-process-modal.js
src/smart-components/order/cancel-order-modal.tsx
src/smart-components/order/order-detail/order-toolbar-actions.tsx
src/smart-components/order/orders-list.tsx
src/smart-components/platform/platform-templates.js
src/smart-components/portfolio/portfolio-empty-state.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/remove-portfolio-modal.tsx
src/smart-components/portfolio/toolbars/portfolios-primary-toolbar.js
src/smart-components/products/products.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap

https://issues.redhat.com/browse/SSP-1934

Add ouiaId to buttons

---

src/helpers/shared/helpers.tsx
src/smart-components/order/order-detail/order-detail-menu.tsx
src/smart-components/order/order-detail/order-lifecycle.tsx

https://issues.redhat.com/browse/SSP-1957

Only display the artifacts box when artifacts are present

---

src/smart-components/common/edit-approval-workflow.tsx
src/smart-components/dialog-routes/portfolio-routes.tsx

Fixes https://issues.redhat.com/browse/SSP-2034

Refresh portfolio after setting approval

---

src/smart-components/common/order-modal.tsx

Update the order modal commit button label.
https://issues.redhat.com/browse/SSP-1670

Change order modal button to Confirm

---

src/constants/routes.ts
src/messages/labels.messages.ts
src/messages/orders.messages.ts
src/redux/reducers/order-reducer.ts
src/smart-components/common/order-modal.tsx
src/smart-components/order/order-detail/order-detail.tsx
src/smart-components/order/order-detail/order-toolbar-actions.tsx
src/test/smart-components/order/orders.test.js
src/types/common-types.d.ts

Implements https://issues.redhat.com/browse/SSP-2068
Before:
After:

Reorder feature

---

src/messages/platforms.messages.ts
src/smart-components/platform/platforms.js

https://issues.redhat.com/browse/SSP-1969
No data:
No filtered results:
Non-admin user:

Update platforms empty pages for no data/no results 

---

src/smart-components/order/order-detail/approval-request.tsx
src/smart-components/order/order-status-mapper.tsx

https://issues.redhat.com/browse/SSP-2077
Before:
After:

Fix for the approval order parmeter overflow

---

src/helpers/order/new-order-helper.ts
src/helpers/order/order-helper.ts
src/helpers/platform/platform-helper.ts
src/helpers/portfolio/portfolio-helper.ts
src/test/integration/portfolio-item-integration.test.js
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/platform/platform-inventories.test.js
src/test/smart-components/platform/platform-templates.test.js
src/test/smart-components/platform/service-offering/service-offering-detail.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/utilities/constants.ts

Replace topological-inventory to catalog-inventory

Replace topological-inventory to catalog-inventory

---

src/helpers/order/new-order-helper.ts
src/helpers/order/order-helper.ts
src/helpers/platform/platform-helper.ts
src/helpers/portfolio/portfolio-helper.ts
src/test/integration/portfolio-item-integration.test.js
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/platform/platform-inventories.test.js
src/test/smart-components/platform/platform-templates.test.js
src/test/smart-components/platform/service-offering/service-offering-detail.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/utilities/constants.ts

Reverts the temporary RedHatInsights/catalog-ui#901

Revert "Replace topological-inventory to catalog-inventory"

---

src/messages/portfolio.messages.ts
src/smart-components/portfolio/portfolio-empty-state.js

https://issues.redhat.com/browse/SSP-1968

Update portfolio empty page

---

src/helpers/order-process/order-process-helper.ts
src/redux/actions/order-process-actions.ts

Fixes https://issues.redhat.com/browse/SSP-2108

Fixed api calls for updating the before and after portfolio items for an order process

---

src/messages/portfolio.messages.ts
src/smart-components/portfolio/portfolios.js

https://issues.redhat.com/browse/SSP-1967

Update the empty portfolios page

---

src/constants/routes.ts
src/helpers/platform/platform-helper.ts
src/messages/labels.messages.ts
src/messages/platforms.messages.ts
src/presentational-components/shared/top-toolbar.tsx
src/smart-components/platform/platform-details.js
src/smart-components/platform/platform.js
src/test/redux/actions/platform-actions.test.js
src/toolbar/schemas/platforms-toolbar.schema.js
src/toolbar/toolbar-mapper.tsx

https://issues.redhat.com/browse/SSP-2116
( no UX mocks yet )

Add platforms detail tab

---

src/helpers/platform/platform-helper.ts
src/presentational-components/platform/platform-card.tsx
src/redux/actions/platform-actions.ts
src/test/integration/portfolio-item-integration.test.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/redux/actions/platform-actions.test.js
src/test/smart-components/platform/platforms.test.js
src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
src/test/smart-components/portfolio/portfolio.test.js
src/types/common-types.d.ts

https://issues.redhat.com/browse/SSP-2123
Add labels for 'Availability status' and 'Enabled' as well as the date of the last refresh to the platform cards:

Add more information to the platform cards

---

src/helpers/platform/platform-helper.ts
src/messages/platforms.messages.ts
src/presentational-components/platform/platform-card.tsx
src/presentational-components/portfolio/portfolio-card-header.tsx
src/presentational-components/shared/card-common.tsx
src/redux/action-types.ts
src/redux/actions/platform-actions.ts
src/redux/reducers/platform-reducer.ts
src/smart-components/platform/platform-details.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap

https://issues.redhat.com/browse/SSP-2122
No UX yet.
- Refresh button added to the platform cards, with I18N tooltip:
- Last refresh message:
-

Add refresh links for platforms

---

src/smart-components/platform/platform-details.js

Separate lines in the last refresh message

---

src/messages/platforms.messages.ts
src/test/smart-components/platform/__snapshots__/platform-details.test.js.snap
src/test/smart-components/platform/platform-details.test.js

Replace the MQtt id display name. Add platform details test

Replace the MQtt id display name. Add platform details test

---

src/helpers/order-process/order-process-helper.ts
src/redux/actions/order-process-actions.ts

Cherry pick from https://github.com/RedHatInsights/catalog-ui/pull/916

[PROD_BETA] Update order process edit

---

src/smart-components/survey-editing/survey-editor.js

This adds an initial implementation for selecting an initial value from pre-defined enum. Please ignore that other fields in the demo (like name and label) also use select input, it's there just for testing purposes.
This is how it works. Instead of creating a new type of field, we just replace the existing input component and add a slight modification. If the schema contains `initialValueOptions` array with one or more items, instead of input we show creatable select. Select gives the option to either pick from existing values or create a new one.
I think, eventually this might make it into the core of the form builder library, but I can't give you a date because we have some other changes planned.
@mkanoor @lgalis feel free to suggest any changes, this is just an early draft. I don't …

Add initial value options selection.

---

src/forms/set-portfolio-item.schema.ts
src/helpers/order-process/order-process-helper.ts
src/test/smart-components/order-process/add-order-process-modal.test.js

Fixes https://issues.redhat.com/browse/SSP-2142
Before:
After:

Add initial lookup parameter to loadProductOptions

---

src/smart-components/survey-editing/survey-editor.js

Fixes https://issues.redhat.com/browse/SSP-2167

Survey editor - Update initial value options  for the input field 

---

src/messages/labels.messages.ts
src/messages/platforms.messages.ts
src/smart-components/platform/platform-details.js
src/smart-components/platform/platform.js
src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
src/toolbar/schemas/platforms-toolbar.schema.js

https://issues.redhat.com/browse/SSP-2148

Platform details page update

---

.travis/custom_release.sh

Update for the rename of master branch to main. Push to qa as well as ci

Update for the rename of master branch to main. Push to qa as well as ci

---

package-lock.json
src/messages/platforms.messages.ts
src/presentational-components/shared/content-gallery-empty-state.tsx
src/smart-components/platform/platforms.js
src/utilities/constants.ts

Add platform doc link to the platforms empty message. Remove Go to sources button.

Add platform doc link to the platforms empty message

---

package-lock.json
package.json
src/helpers/order-process/order-process-helper.ts
src/test/helpers/order-process/order-process-helper.test.js
src/test/helpers/order/new-order-helper.test.js
src/test/integration/portfolio-share-workflow.test.js
src/test/presentational-components/platform/platform-card.test.js
src/test/smart-components/common/edit-approval-workflow.test.js
src/test/smart-components/portfolio/add-portfolio-modal.test.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
src/test/smart-components/portfolio/portfolio.test.js
src/test/smart-components/portfolio/portfolios.test.js
src/test/smart-components/products/products.test.js

https://issues.redhat.com/browse/SSP-2234

Fix for create order process with no 'after' portfolio item

---

src/redux/actions/order-actions.tsx

Fixes https://issues.redhat.com/browse/SSP-2272

Remove duplicate Order word from the cancel order message

---

src/smart-components/order/order-detail/order-lifecycle.tsx

Fixes https://issues.redhat.com/browse/SSP-2243

Remove the card with the manage product link from the lifecycle tab

---

src/presentational-components/shared/top-toolbar.tsx

Fixes https://issues.redhat.com/browse/SSP-2346

Change title type to PageHeaderTitle

---

src/App.js

Remove blocking for the first nav event, which was a workaround for chrome 1
Fixes https://issues.redhat.com/browse/SSP-2444

Fix for first sub-menu catalog navigation

---

src/helpers/order/service-plan-helper-s.ts
src/redux/reducers/i18n-reducer.ts
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/survey-editing/survey-editor-s.js

Implements https://issues.redhat.com/browse/SSP-2457
( After saving m the modified service plan should be displayed, but the base is instead until https://issues.redhat.com/browse/SSP-2496 is fixed ).

Standalone service plan apis

---

package-lock.json
src/constants/routes.ts
src/helpers/order/new-order-helper-s.ts
src/helpers/order/order-helper-s.ts
src/helpers/order/service-plan-helper-s.ts
src/helpers/portfolio/portfolio-helper-s.ts
src/helpers/shared/orders.ts
src/presentational-components/navigation/routes.js
src/redux/actions/order-actions-s.tsx
src/redux/reducers/order-reducer.ts
src/smart-components/common/order-modal.tsx
src/smart-components/order/orders-list.tsx
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/standalone-nav.js
src/test/utilities/__snapshots__/use-format-message.test.js.snap
src/utilities/constants.ts

Implements https://issues.redhat.com/browse/SSP-2438
Update most order Api endpoints. Order create/submit is complete. Order list will have to wait for the GET order_items endpoint implementation.

Standalone order api update - part 1

---

src/helpers/shared/active-user.js
src/helpers/shared/active-user.ts
src/helpers/shared/user-login.ts
src/presentational-components/navigation/stateful-dropdown.js
src/routing/catalog-route-s.js
src/smart-components/order/order-item.tsx
src/standalone-nav.js

Standalone - add current user and logout menu to the application header

---

config/dev.webpack.config.js
package-lock.json
src/helpers/order/service-plan-helper-s.ts
src/helpers/shared/user-login.ts
src/redux/reducers/order-reducer.ts
src/smart-components/common/order-modal.tsx
src/smart-components/survey-editing/survey-editor-s.js

https://issues.redhat.com/browse/SSP-2600

Standalone - updated service plan endpoints

---

src/helpers/rbac/rbac-helper-s.ts
src/helpers/share/share-helper-s.ts
src/redux/actions/rbac-actions-s.ts
src/redux/actions/share-actions-s.ts
src/smart-components/order/order-detail/order-detail.tsx
src/smart-components/order/order-detail/order-details.tsx
src/smart-components/portfolio/share-portfolio-modal.tsx
src/utilities/constants.ts

https://issues.redhat.com/browse/SSP-2439

Standalone UI - group and sharing endpoints

---

src/smart-components/order/order-detail/order-detail.tsx
src/smart-components/order/order-detail/order-details.tsx

Update order details layout

---

config/standalone.prod.webpack.config.js
src/loaders/standalone/AppStandalone.js
src/standalone-nav.js

Updated standalone build dist path to /ui/catalog to match changes in https://github.com/ansible/ansible-catalog/pull/271

Standalone updated build path

---

package-lock.json
package.json

Reverts RedHatInsights/catalog-ui#1149

Revert "Bump @redhat-cloud-services/frontend-components from 3.5.1 to 3.6.1"

---

index.html
src/App.js
src/constants/routes.ts
src/helpers/approval/approval-helper-s.ts
src/messages/approval.messages.ts
src/presentational-components/navigation/routes.js
src/redux/actions/approval-actions-s.ts
src/routing/catalog-route-s.js
src/smart-components/common/edit-approval-workflow.tsx
src/standalone-nav.js
src/test/helpers/approval/approval-helper-s.test.js
src/test/redux/actions/approval-actions-s.test.js
src/test/smart-components/common/__snapshots__/edit-approval-workflow-s.test.js.snap
src/test/smart-components/common/edit-approval-workflow-s.test.js

Update workflow apis.
Updated routes.

Update workflow apis

---

src/presentational-components/platform/platform-card.tsx
src/smart-components/platform/platform-details.js

Fixes https://issues.redhat.com/browse/SSP-2184

Standalone - Remove ansible version from the platform details

---

src/messages/platforms.messages.ts
src/presentational-components/navigation/about-modal/about-modal.tsx
src/presentational-components/platform/platform-card.tsx
src/presentational-components/shared/table-toolbar-view.tsx
src/smart-components/platform/platform-details.js
src/types/common-types-s.d.ts
src/types/common-types.d.ts

Add controller url to the platform details

---

src/App.js

Once we check this in stage, I'll create the banner in production

[stable] Add deprecation banner

---

src/App.js

[prod-beta] Add deprecation banner

---

.travis.yml
package.json
src/App.js

[prod-stable] Add deprecation banner
