RedHatInsights/catalog-ui

src/SmartComponents/Common/AddPortfolioModal.js, src/SmartComponents/Common/Alerts.js, src/Store/Actions/PortfolioActions.js
**What:**
This PR adds Alerts for adding portfolios and fix missing `aria-label` prop for Button with plain variant.
**Screenshots:**
Adding new portfolio:
Cancel adding new portfolio:
Adding new portfolio failed:
**Note:**
For now, adding new portfolio is failing because portfolio items were removed, and this is not related to adding Alerts.
=> Add Alerts for adding portfolios and fix missing aria-label prop

src/Routes.js, src/SmartComponents/ServicePortal/PortalNav.js, src/SmartComponents/ServicePortal/portalnav.scss, src/Store/ActionTypes/UiActionTypes.js, src/Store/Actions/UiActions.js, src/Store/Reducers/UiReducer.js
**What:**
Add _Edit_ icon for any portfolio displayed while hovering on portfolios name in the list of Portfolios, add new action, action type, Ui reducer (we need to know if we are editing the portfolio or not), support React routing, some other small changes.
**Screenshots:**
_All Portfolios_ are selected and _Edit_ icon appears next to some portfolio if we hover on the it:
Clicking on _Edit_ to edit the portfolio (the portfolio becomes selected):
If we click anywhere else, the portfolio remains selected (we will want to click on _Cancel_ to stop editing portfolio - this will coming soon in the next PR):
**Next:**
In the next PR, I will add _Remove_ and _Cancel_ buttons which should appear if clicking on _Edit_ the portfolio from the list of portfolios, above the portfolio items.
=> Add ability to edit Portfolios

src/Routes.js, src/SmartComponents/Platform/PlatformItems.js, src/SmartComponents/Portfolio/Portfolio.js, src/SmartComponents/Portfolio/PortfolioItems.js, src/SmartComponents/ServicePortal/PortalNav.js
Fixes issues with routes redirecting to root route and also adds client-side ui routing.
The route path is defined like this `/platform_items/:filter?`
But the link redirects you to this: `foo.redhat.com:1337/insights/platform/service-portal/platform_items/platform=1`
The router expects this string: `/platform_items/1`, but it gets `platform_items/platform=1`
Also routes where you expect changes in params cannot be marked as `exact` because the route will be changing by definition.
Also i have removed optional parameters from some routes, because there is no fallback component for case thet you did not provide params (all components expect id parameters to exist). Now the root route will be used instead.
=> Use react routing.

src/App.js
For some reason after the `App` component is mounted, it pushes some url to history. Pushed location was invalid and it was causing redirect to root route. I've commented it right now and will investigate further.
=> Removed APP history listener.

src/PresentationalComponents/Portfolio/AddProductsTitleToolbar.js, src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js, src/PresentationalComponents/Shared/404Route.js, src/SmartComponents/Portfolio/AddProductsToPortfolio.js, src/SmartComponents/Portfolio/Portfolio.js, src/redux/Actions/PortfolioActions.js
Switching between views for list of portfolio products and add products to portfolio was handled via react state. That is probably not something we want.
I've replaced it with react routing so the user is not redirected to different page after refresh and we can use history.
I've also noticed that we use something similar for add/edit modals. I think we should also add routing to these. We will be able to simplify all components using `MainModal` component and Remove the MainModal reducer. That is for future PR.
=> Added routing for portfolio actions.

package.json
Fixes build error `Uncaught Error: Cannot find module '@patternfly/react-tokens'`
This occurs after updating PF version. They have changed they build in minor release once again.
=> Added pf react tokens to dependencies.

src/Utilities/store.js
Adds keys to automatic error notification. We can now start removing manual handling of error messages for API requests.
- SSP API (errors)
- low level javascript error message (message, stack)
We can add more in the future for other APIs (when we know what error format we get.)
=> Added error message keys to notifications configuration.

package.json
Error on dev cluster :
Error: Cannot use e "__Schema" from another module or realm. Ensure that there is only one instance of "graphql" in the node_modules directory. If different versions of "graphql" are the dependencies of other relied on modules, use "resolutions" to ensure only one version is installed. https://yarnpkg.com/en/docs/selective-version-resolutions Duplicate "graphql" modules cannot be used at the same time since different versions may have different capabilities and behavior. The data from one version used in the function from another could produce confusing and spurious results.
=> Add graphql

src/PresentationalComponents/Shared/FilterToolbarItem.js, src/SmartComponents/Common/PlatformSelectToolbar.js, src/SmartComponents/Portfolio/AddProductsToPortfolio.js
Added filtering to products in portfolios.
Note: If there is a lot of items, rendering performance will take a hit. It would be nice to have server-side filtering and paging at some point in the future. I can do some optimization on the front end, but it wont help you have hundreds or thousands of items on screen it.
=> Added filtering for products.

src/SmartComponents/ContentGallery/ContentList.js
There was an error in runtime when rendering orders table:
This was caused by faulty table header generator. It assumed that the first order will always have all the columns defined. If that is not a case the table body will be rendered fine. But if some row has additional data, it will reference header column that does not exist at ui will crash.
I've created header generator that will always create headers from row with largest amount of columns. 
Note, that this is not exactly clean approach, but because i plan to migrate to PF4 table component soon i will create better way to define the table contents then.
Also the loader placeholder was in wrong code branch.
=> Fixed header generating form orders table.

src/PresentationalComponents/Portfolio/AddProductsTitleToolbar.js, src/SmartComponents/Portfolio/AddProductsToPortfolio.js
Change Add Products button type and set to disable when no products are selected
=> Change Add Products button type and set to disable when no products are selected

config/base.webpack.plugins.js, src/Helpers/Shared/userLogin.js, src/Utilities/Constants.js, src/test/redux/actions/portfolio-actions.test.js
Additionally, use the BASE_PATH env var as part of the API paths
@martinpovolny @Hyperkid123 Please review.  Let's also discuss before merge because I need to change the travis environment to have BASE_PATH set properly (and less importantly, so I can remove the rest of the env vars defined there).
=> Cleanup unused env vars and rename for clarity

config/setupTests.js, package-lock.json, package.json, src/App.js, src/Helpers/Platform/PlatformHelper.js, src/test/.eslintrc, src/test/redux/actions/platform-actions.test.js
Requests for service offerings are now filtering out archived entities. This required a custom API call because API clients does not support filtering features yet.
- custom API call for service offerings
- added polyfill for `fetch`: https://www.npmjs.com/package/whatwg-fetch
- adjusted tests to work with fetch API
=> Non archived service offerings

src/Utilities/store.js, src/redux/Actions/PortfolioActions.js
Adds notifications key to show API error responses for portfolio entities. Based on https://github.com/ManageIQ/service_portal-api/pull/107
=> Added api error key form portfolio validation.

src/App.js, src/PresentationalComponents/Shared/LoaderPlaceholders.js
Fixes issue with unauthorized error after login. 
Chrome sends authorization TOKEN to ui before it is sent to APIs. So the UI loads but the user is not authorized in APIs so the requests will throw an error.
Adds a workaround. UI waits on auth token from chrome (the same that is sent to API) and shows placeholder until auth token is received. This should be solved in chrome , but because they don't own the auth service they cannot do this right now. Maybe they will come up with something in a future.
=> Fixed unauthorized error

src/Helpers/Order/OrderHelper.js, src/redux/Actions/OrderActions.js, src/test/redux/actions/order-actions.test.js
Some notes:
Seems to that creating order is not an atomic operation on API side. Do we have some scenario what happens when some stage of this process fails?
=> Added tests for orders redux action creators.

package-lock.json, src/Helpers/Portfolio/PortfolioHelper.js, src/SmartComponents/Common/MainModal.js, src/SmartComponents/Order/OrderServiceFormStepConfiguration.js, src/test/redux/actions/portfolio-actions.test.js
- Are these supposed to show for every portfolio or only for some kind. If so, how can i tell when to make this request?
- Do we know where the select field should be? On the top/bottom somewhere else?
- Thanks to the nested structure of JSON schema, output data format of the for for the destination will be nested. What is the expected data format? Is it just a random object? Right now the generated docs does not specify how the data should look like.
```javascript
{
name: 'Foo',
description: 'Bar',
providerControlParameters: {
namespace: 'default'
}
}
``` 
- New API clients returns instances of classes. That will hurt us in a long run. Right now it enforces using classes in only tests. This would be fine if we are creating these objects in UI but everything is done via API and will add …
=> Added selection of destination project for order modal

.eslintrc.yml, package.json, src/PresentationalComponents/Shared/pf4-select-wrapper.js, src/SmartComponents/Common/FormRenderer.js
Fixes issue with PF4 select not handling empty input value.
- upgrade insights fronted components. Fixes transparent background
- Adds empty option to select if no value is selected
- empty option with value `undefined` will not let user submit the form until he chooses something
- why not add initial value? We cannot hard code initial value because we don't know what fields and values will be send from API. Also API response does not include default value.
=> Custom select

src/App.scss, src/PresentationalComponents/Platform/PlatformItem.js, src/PresentationalComponents/Platform/platformcard.scss, src/PresentationalComponents/Shared/CardCommon.js, src/PresentationalComponents/Shared/service-offering-body.js, src/SmartComponents/Portfolio/PortfolioItem.js, src/SmartComponents/Portfolio/portfolioitem.scss
I've noticed that topological API now returns more data that is closer match to our mocks.
- updated displayed information
- remove duplicate code (platform/portfolio cards) and created common card component
- update layout styling for service offering cards
- ServiceOffering response payload
- ~~The service offering response from TopologicalAPI gives me more data (display name, distributor etc.) than the portfolio items SSP API response. This means that portfolio items does not have complete information about the service offering~~.
=> Service offering card update

package-lock.json, package.json, src/App.js
Should fix an issue with older browsers that does not support `scroll` methods on Element prototype.
=> Added scroll polyfill to support older browsers.

src/presentational-components/platform/platform-toolbar.js, src/test/presentational-components/platform/__snapshots__/platform-toolbar.test.js.snap
- moved pagination bar on platform items screen to the right to match PF guidelines.
=> Fixed pagination alignment in platform items screen.

src/presentational-components/shared/breadcrubms.js
Removes breadcrumbs from first level pages to match mocks. Now will only show there there are two or more levels of nesting. 
Affected routes
- /portfolios
- /platforms
- /orders
=> Removed breadcrumbs with only one level.

package-lock.json, package.json, src/presentational-components/shared/card-common.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap, src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
I've replaced the CSS with react component. Its not pretty but if we want multi line ellipsis effect there is no other way unfortunately. Firefox simply does not support `line-clamp` CSS property.
=> Fix card line clamping in Firefox.

src/presentational-components/shared/content-gallery-empty-state.js, src/smart-components/content-gallery/content-gallery.js, src/smart-components/platform/platforms.js, src/smart-components/portfolio/portfolio.js, src/smart-components/portfolio/portfolios.js, src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap, src/test/smart-components/portfolio/portfolio.test.js
- added empty states for platforms portfolios and portfolio screens (not add/remove portfolio item screens)
- Icons is mostly subject to change but changing that is just a matter of importing different icon from PF.
All of them look similar just different text
=> Empty states for platforms portfolios and portfolio screens

config/base.webpack.config.js, package.json
- CSS assets were not build in production environment
- webpack tree shaking was also removing all scss files because they were not explicitly referenced.
- added SCSS files to sideeffects
- also using just `MiniCssExtractPlugin` instead of `style-loader`.
=> Fixed webpack SCSS tree shaking.

src/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.js, src/smart-components/portfolio/add-products-to-portfolio/index.js, src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-gallery.test.js.snap
- added empty states for add products to portfolio screen
- one when no platform is selected
- one when filter does not match any products
- this is going to change probably soon. Just wanted to get rid of that ugly string
=> Added empty states for add products to portfolio screen.

src/App.scss, src/presentational-components/portfolio/portfolio-filter-toolbar.js, src/smart-components/portfolio/portfolio.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
- moved portfolio share, edit, dropdown buttons to the top part of toolbar.
=> Moved portfolio toolbar buttons.

src/presentational-components/shared/pf4-select-wrapper.js
**Description**
- Fix props warning of PF4 Select wrapper
**Before**
```javascript
Warning: Failed prop type: The prop `fieldId` is marked as required in `FormGroup`, but its value is `undefined`.
Warning: Failed prop type: FormSelect requires either an id or aria-label to be specified
Warning: React does not recognize the `formOptions` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formoptions` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Warning: Invalid DOM property `dataType`. Did you mean `datatype`?
```
@Hyperkid123
=> Fix PF4 select wrapper props warnings

src/smart-components/order/create-order-row.js
- added correct icon for failed order step
- Add Order initiated override that will show success icon if it did not fail and approval was already approved
- hide step info after first failed step.
=> Added correct icons to order steps.

src/smart-components/common/order-modal.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
- fixed wrong icon for order modal
- fixed Heading sizing
- added portfolio display name to order modal header
fixes: #175
=> Fixed order modal header icon and text sizing.

src/smart-components/order/order-item.js
Adds owner to order header.
Solves #177
=> Added owner to order header.

src/smart-components/order/create-order-row.js
- more info about state for order steps: https://github.com/ManageIQ/catalog-ui/issues/173#issuecomment-486568497
solves #173 
- added correct highlight to failed order steps
- order initiated is always shown as successful
=> Fixed failed order step highlight.

src/redux/action-types.js, src/redux/reducers/approval-reducer.js, src/redux/reducers/order-reducer.js, src/redux/reducers/platform-reducer.js, src/redux/reducers/portfolio-reducer.js, src/redux/reducers/rbac-reducer.js, src/redux/reducers/share-reducer.js, src/utilities/loading-state-middleware.js, src/utilities/store.js
- New redux middleware for rejected actions
- is triggered by rejected action creator
- sets loading state to false in redux store
- UI no longer "spins" after unsuccessful requests
- Added new key to response messages (data.message)
solves: #181 and #182
=> Added global redux rejected loading handler.

src/smart-components/order/order-messages-modal.js
- horizontal scroll bar to progress messages modal.
Is caused by wrong response format on the message attribute. Sometimes it returns ruby hash instead of JSON so its nor formatted properly by `JSON.stringyfy`.
=> Added horizontal scroll to progress message modal.

src/App.scss, src/helpers/order/order-helper.js, src/redux/actions/order-actions.js, src/smart-components/order/create-order-row.js, src/smart-components/order/order-detail-table.js, src/smart-components/order/order-item.js
solves: https://github.com/ManageIQ/catalog-ui/issues/190
- wrong steps progress when order was successfully finished
- wrong progress when request was denied
- red highlight color on failed order step number
- moved highlight to step in progress from last finished step
- added manage product link if the order was completed
If the approval request has state `denied` and the whole order has state `Denied`
=> Fixed steps highlighting and progress.

src/presentational-components/shared/pf4-select-wrapper.js, src/redux/reducers/portfolio-reducer.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
Adds back the link which takes the user to edit mode for portfolio item
- enables workflow edit from portfolio item detail screen
- mostly revert of https://github.com/ManageIQ/catalog-ui/pull/152/files
=> Enable portfolio item workflow edit.

src/helpers/portfolio/portfolio-helper.js, src/redux/actions/portfolio-actions.js, src/smart-components/portfolio/portfolio.js, src/toolbar/schemas/portfolio-toolbar.schema.js
- adds copy portfolio modal
Currently the copy portfolio endpoint does not accept `name` or `share with the same groups attributes` as is showed on mocks: https://redhat.invisionapp.com/d/main#/console/16104390/365986228/preview
=> Added copy portfolio modal.

src/presentational-components/portfolio/portfolio-card-header.js, src/presentational-components/portfolio/portfolio-card.scss, src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
If the portfolio title was too long the text was overflowing the card and button actions were pushed to next line.
Thanks @lgalis for noticing this
=> Fix portfolio card header overflow.

src/App.scss, src/redux/actions/portfolio-actions.js, src/redux/reducers/portfolio-reducer.js, src/smart-components/portfolio/portfolio-item.js, src/smart-components/portfolio/portfolio.js, src/test/redux/actions/portfolio-actions.test.js, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap, src/test/smart-components/portfolio/portfolio.test.js
- switched order of async calls when removing portfolio items
- undo notification is not showed until items are removed, list is updated and rendered
- portfolio items list update is now part of the remove action instead of being called after remove is finished
- added state mutation on portfolio items remove pending/success
- this causes the add/remove items buttons to be disabled correctly
- added disabled state to portfolio items while item is being removed
- adds gray overlay
- disables events on card (user can no longer redirect to item which is being deleted)
=> Added disabled state to portfolio items in content gallery.

package-lock.json, package.json, src/helpers/portfolio/portfolio-helper.js, src/presentational-components/shared/pf4-select-wrapper.js, src/redux/actions/portfolio-actions.js, src/smart-components/common/form-renderer.js, src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap, src/test/presentational-components/shared/pf4-select-wrapper.test.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
@syncrou @gmcculloug I have a question about the new portfolio name. UI renders the `display_name` attribute of portfolio item because that is the human readable equivalent of `name` but the copy endpoint changes the `name` attribute so the `display_name` is unchanged. 
I belive the `display_name` should be modified instead. Any thoughs?
(endpoint PR: https://github.com/ManageIQ/catalog-api/pull/289)
- added copy portfolio item modal
- mocks: https://docs.google.com/presentation/d/1Z0Jd5JQa1eavch_ZbTJ8YkDjRZpu6twyece1T-k8xOw/edit#slide=id.g5b73dafedf_0_47
=> Added copy portfolio item feature.

src/smart-components/portfolio/portfolio-item.js
- portfolio item card was not rendering link on selectable cards
(caused by: https://github.com/ManageIQ/catalog-ui/pull/222/files#diff-4701f3d3e807955fb77dc7e28ba59048L175)
=> Fix portfolio-item-card link.

src/App.scss, src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap, src/toolbar/helpers.js
- links on toolbars were clickable even when they were in `disabled` state
- disabled all pointer events if toolbar link is marked as `disabled`
=> Disabled pointer events on disabled toolbar links.

package-lock.json, package.json, src/presentational-components/shared/pf4-select-wrapper.js, src/smart-components/order/order-service-form-step-configuration.js
~~Merge only after https://github.com/data-driven-forms/react-forms/pull/26. There was a bug with argument assignment to one of the validator types.~~
- no visual changes
- added simple function that creates correct schema for order modal form
- there is no explicit way to identify schema from Openshift, that should be added
- now we can order items from both openshift and Tower
=> Modified order modal to accept different UI schema types.

src/presentational-components/shared/service-offering-body.js
Show description on product cards instead of long description. Long description is used as fallback instead to minimize the change of having empty cards.
=> Show description instead of long_description on product card.

src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
- empty attributes are no longer showing on portfolio item detail
- removed sample repository link because it was always a dead link
- removed duplicate description text and move overview section to the top
=> Hide empty attributes in product detail page.

src/smart-components/portfolio/portfolio-items.js
Fixed message and Add Products link on the Empty Portfolio page
https://projects.engineering.redhat.com/browse/SSP-638
Before:
After:
=> Fixed message and Add Products link on the Empty Portfolio page

src/presentational-components/shared/card-icon.js
`platformId` prop was always set to `undefined`. That caused the fallback Icon not to be set. 
The `undefined` should be in default props but component props have this vale by default it they are not set.
=> Removed platformId undefined override in card icon component.

src/helpers/platform/platform-helper.js, src/helpers/shared/user-login.js, src/redux/actions/platform-actions.js, src/test/redux/actions/platform-actions.test.js, src/test/smart-components/platform/platforms.test.js, src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js, src/test/smart-components/portfolio/portfolio.test.js, src/utilities/store.js
- we only query sources that are of `/insights/platform/catalog` application type
- added graphql API instance
- added interceptor to catch graphql error response and throw it as an actual error
Now we can see only the Tower source (in both platforms and when adding items to portfolios):
=> Filter sources by application type

src/presentational-components/shared/card-icon.js, src/smart-components/order/orders.js
- Orders icons
- reproduce: reload browser on orders screen
- orders require platforms to get default icons, but when going directly on orders page, platforms are not loaded so there are no data to pick default icon
- this is continuation of a workaround until we have default icons from APIs
=> Fetch platforms before showing orders.

src/redux/actions/order-actions.js
This PR fixes the following error that occurs when cancelling an order:
=> Fixed post cancel order list and success message

src/constants/nullable-attributes.js, src/forms/portfolio-form.schema.js, src/helpers/portfolio/portfolio-helper.js, src/helpers/shared/user-login.js, src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap, src/test/smart-components/portfolio/add-portfolio-modal.test.js, src/test/smart-components/portfolio/portfolio.test.js
- added clear able option to to workflow select
- now that the options are loaded asynchronously, server does not return an empty options obviously
- clear able select has addition button which deletes the value
- Fixed empty description was not saved
- when value is deleted from formState its value is `undefined` but API expects `null`
- Fixed URL freeze when trying to save portfolio which has `%` in name
- this was caused by async validation because the API client is not serializing special characters
- query was `?filter[name]=%%%` instead of `?filter[name]=%25%0A%25%0A%25%0A.`
- I will create interceptor function in the JS clients library to cover the rest of platform apps
=> Fixed add/edit portfolio modal

src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
- empty vendor name is now hidden
Before:
After:
=> Hide vendor data when its empty in portfolio item detail.

config/spandx.config.js
**Description**
Because the catalog menu section contains the approval app, which is not a part of the catalog application, spandx needs to be updated to overwrite only catalog apps.
@karelhala
=> Overwrite only catalog apps in spandx.config

config/setupTests.js, src/presentational-components/order/order-notification.js
- use chrome API to trigger navigation highlight when navigating to orders via notification link.
=> Fixed order navigation highlight.

src/constants/nullable-attributes.js, src/forms/edit-portfolio-item-form.schema.js, src/helpers/shared/orders.js, src/presentational-components/shared/breadcrubms.js, src/redux/actions/portfolio-actions.js, src/smart-components/common/order-modal.js, src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
UI side of: https://github.com/ManageIQ/catalog-api/pull/428
Depends on: https://github.com/ManageIQ/catalog-api/pull/429
~~Currently i am having an issue with API so I was not able to test it in UI. I want to wait until ill be able to do that.~~
~~(I did contacted Drew about the API issue: `error: "invalid value for "operation", must be one of #{validator.allowable_values}."`)~~
- removed usage of `display_name` from catalog entities.
=> Removed usage of display_name from catalog objects.

src/redux/actions/portfolio-actions.js
Fixes https://projects.engineering.redhat.com/browse/SSP-725
The existing UX mocks do not have a description nor are dismissable - but the notifications should have a consistent look.
@sbuenafe
=> Add a description and make the notification for the copy portfolio dismissable

src/forms/edit-portfolio-item-form.schema.js
UI follow up of: https://github.com/ManageIQ/catalog-api/pull/438
cc @syncrou while testing locally i am still seeing the validation error like:
`#/components/schemas/PortfolioItem/properties/distributor don't allow null`
=> Rmoved required validations from portfolio item form.

src/smart-components/portfolio/share-portfolio-modal.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js, src/utilities/constants.js
Update the catalog portfolio permissions sharing verbs. 
limit the permission verbs to be updated via the UI to the ones in permissionValues array.
=> Update catalog portfolio permissions sharing verbs

src/forms/edit-portfolio-item-form.schema.js
Product description is not required via the `PortfolioItem` model https://github.com/ManageIQ/catalog-api/blob/master/app/models/portfolio_item.rb#L11 so removing the `isRequired` in the schema.
This depends on https://github.com/ManageIQ/catalog-api/pull/441
There is still more work to be done for the edits to fully work.
For any `patch` operation all `readOnly` params need to be stripped from the payload:
```
found unpermitted parameters: :id, :service_offering_source_ref, :service_offering_type, :portfolio_id
```
Product edits will work once https://github.com/ManageIQ/catalog-api/pull/441 is merged and the `readOnly` attributes are removed from the `patch` payload.
=> Removed isRequired from product description

src/helpers/portfolio/portfolio-helper.js, src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
- fixed unpermitted parameters in edit portfolio item payload
- params `id, service_offering_source_ref, portfolio_id` are removed from object before calling the API
=> Fixed unpermitted parameters in edit portfolio item payload.

src/App.js, src/Routes.js, src/helpers/portfolio/portfolio-helper.js, src/helpers/shared/helpers.js, src/redux/action-types.js, src/redux/actions/portfolio-actions.js, src/redux/reducers/open-api-reducer.js, src/test/__mocks__/open-api-mock.js, src/test/redux/actions/portfolio-actions.test.js, src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js, src/test/utilities/store.test.js, src/utilities/store.js
- to avoid constant updates of unpermitted when updating catalog entities i added automatic cleanup based on openApi schema from `/api/catalog/v1.0/openapi.json` hosted in cloud services.
Related to: https://projects.engineering.redhat.com/browse/SSP-877 and many others. After this it should be automated.
=> Sanitize patch requests based on openApi schema

src/presentational-components/portfolio/porfolio-card.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolio.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/toolbar/schemas/portfolio-toolbar.schema.js
Add the 'Edit approval' to the portfolio detail kebab menu on the Portfolio detail page, and drop the 'workflow from all menus
=> Add the 'Edit approval workflow' to the portfolio detail kebab menu

src/presentational-components/portfolio/porfolio-card.js, src/presentational-components/shared/top-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-items.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/toolbar/schemas/portfolio-toolbar.schema.js
- use different component passing to PF dropdown item
- their type checking only allows ReactNode instead of any render able node
- removed `isRequired` from top toolbar prop type checking
- use default prop for top toolbar title instead of checking it in each render cycle
=> Fixed minor prop types errors

.dependabot/config.yml
Dependabot is spamming PRs every time any of selected packages is updated.
I added weekly restriction to it so we wont be reviewing dependabot PRs all the time.
=> Run weekly updates on dependabot.

src/presentational-components/shared/card-icon.js
- icon fallback had higher priority than the actual source and was used even if the icon existed
=> Fixed icon source fallback priority

src/App.scss, src/helpers/order/order-helper.js, src/smart-components/common/async-pagination.js, src/smart-components/order/orders-list.js, src/test/smart-components/order/orders.test.js
- added async filtering to orders view
As you can see the poor performance really starts to show. User is just mostly looking at loading screen. I think that we should bring back the discussions about better way to get the data from server. A basically have to create 3 sequential requests because each sub collection depends on the previous one
=> Orders async filtering

src/smart-components/portfolio/portfolio-item.js, src/smart-components/portfolio/portfolio.js, src/smart-components/products/products.js, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
- links in products pages are now disabled
- links are disabled if source or portfolio of portfolio item no longer exist
- fixed links for existing items (it was using the old non query params links)
=> Disabled non-existing products links.

src/smart-components/portfolio/share-portfolio-modal.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js, src/utilities/constants.js
Updated permission verbs to the new version that removes the app name and resource type.
Should be merged after https://github.com/RedHatInsights/catalog-api/pull/500.
/cc @mkanoor
=> Updated permission verbs to the new version

src/smart-components/common/edit-approval-workflow.js, src/smart-components/platform/platform-inventories.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolios.js, src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap, src/test/smart-components/common/edit-approval-workflow.test.js
Use portfolio/resource name in modal titles for set approval workflow and the portfolio name in the share/edit portfolio modal titles.
https://projects.engineering.redhat.com/browse/SSP-1103
=> Use portfolio/resource name in modal titles

src/helpers/shared/pagination.js, src/presentational-components/shared/content-gallery-empty-state.js, src/presentational-components/shared/top-toolbar.js, src/redux/actions/order-actions.js, src/redux/actions/portfolio-actions.js, src/redux/reducers/portfolio-reducer.js, src/smart-components/order/orders-list.js, src/smart-components/portfolio/portfolio-empty-state.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolios.js, src/smart-components/products/products.js, src/test/redux/actions/portfolio-actions.test.js, src/test/redux/reducers/portfolio-reducer.test.js, src/test/smart-components/order/orders.test.js, src/test/smart-components/portfolio/portfolio.test.js, src/test/smart-components/portfolio/portfolios.test.js, src/toolbar/schemas/portfolio-toolbar.schema.js, src/toolbar/schemas/portfolios-toolbar.schema.js, src/toolbar/schemas/products-toolbar.schema.js, src/utilities/empty-data-middleware.js, src/utilities/store.js
- added redux middleware which adds `noData` flag
- the flag is set to true when API response count is 0 and no filter was applied
- added empty states variants for `noData` scenario
- completely removed toolbar actions when `noData` is set. User will use primary actions from empty states
The same pattern is applied to all entities with exception of platforms (There are some missing API features to enable pagination/filter)
=> Empty states when server has no data

.dependabot/config.yml
The preferred schedule is weekly.  The additional "live" setting is not needed.
=> Remove extra `update_schedule` setting from dependabot config

src/redux/actions/portfolio-actions.js, src/test/redux/actions/portfolio-actions.test.js
- when removing portfolio items from a portfolio, the filter attribute was missing and the empty data middleware crashed in runtime.
=> Added missing filter attribute to remove portfolio item.

src/smart-components/portfolio/share-portfolio-modal.js
- added `unsharePortfolio` to `bindActionsCreators`
unshare actions were not dispatched as redux actions, therefore the redux notification middleware did no catch the fulfilled message.
=> Fixed missing dispatch bind on unshare portfolio action.

src/presentational-components/platform/platform-item.js, src/presentational-components/shared/service-offering-body.js
- apply fallback icon for service offerings cards
=> Fixed missing icons for service offerings.

src/smart-components/common/edit-approval-workflow.js
Follow up for # 390 - update handling of empty workflow selection
Note: initialValues not working after the DDF upgrade
=> Update handling of empty workflow selection

package-lock.json, package.json, src/helpers/platform/platform-helper.js, src/helpers/shared/user-login.js, src/test/helpers/shared/user-login.test.js
This is a first of series of PR which focuses on bundle size optimizations. The bigger effect will come after https://github.com/RedHatInsights/frontend-components/pull/340 is merged.
- remove topological inventory client
- remove sources client
The catalog used one or two methods for API calls from each of these libraries. Because they are generated as a class, un-used methods cannot be ever tree shook.
Why is this necessary? By removing the topological inventory client itself, bundle size is reduced by 1 MB. See the relative size bellow. It has roughly the same size as the whole react-core library. The sources client is slightly smaller, but we were using only one method. The rest is handled by graphql calls.
=> Remove unnecessary clients.

src/smart-components/order/order-detail/approval-request.js
- use approval_request_ref instead of id in order detail screen
- the number is now a link that takes the user to approval detail
=> Use approval_request_ref instead of id.

config/webpack.config.js, package-lock.json, package.json, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/survey-editing/survey-editor.js
- the control panel is now part of form builder with getShema and is a valid prop
- disable save survey button when the schema is not valid
- added webpack alias for react
- libraries will always use the react version from catalog
- makes it easier to link packages and avoid possible react duplications
=> Use is valid to disable survey editor submit.

src/App.scss, src/forms/form-fields/shage-group-edit.js, src/forms/form-fields/share-group-select.js
- ~~added max with to the select value container~~
- use grid layout to enforce correct width
- enabled portals for select menus to enable menu overflow over the modal container
- use render function instead of children in FieldProvider to prevent re-initialization after select change
=> Fixed overflow in share portfolio modal.

src/presentational-components/styled-components/level.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
https://projects.engineering.redhat.com/browse/SSP-1283
I went with alert instead of disabling the button. The user must know why the button is available and popovers are totally buggy in PF. But of course, it can be changed if you decide the disabled button is preferable.
Also, I fixed a typo that was forcing the portfolio item name to be aligned to the bottom.
Screenshot from testing:
=> Remove order button when source is unavailable.

src/global-styles.js
- added frontend component class override
For some reason, the CSS rules for `section.ins-l-content` are not making it into a production build bundle. It is probably caused by frontend components, but the cause is unknown so far. This was causing missing spacing in the main layouts:
`section.ins-l-content` was missing in the build bundle but this override inserts it correctly.
=> Fixed missing section.ins-l-content class.

config/webpack.config.js, package.json
fixes: https://projects.engineering.redhat.com/browse/SSP-1316
In production mode, webpack was marking all external CSS files as side effects (never used) so it got rid of them before the style-loader could inject them into the bundle and they never made it to the production build.
That is why we have been missing some CSS in production, but they were in the dev build.
=> Exclude css files from tree shaking.

src/presentational-components/platform/platform-card.js, src/presentational-components/portfolio/porfolio-card.js, src/presentational-components/shared/service-offering-body.js, src/presentational-components/styled-components/card.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
https://projects.engineering.redhat.com/browse/SSP-1329
- hide overflow in PF cards (ellipsis on multi-level overflow does work only in chrome)
=> Fix PF card overflow.

src/smart-components/order/order-detail/order-toolbar-actions.js, src/smart-components/order/order-item.js
jira: https://projects.engineering.redhat.com/browse/SSP-1334
- added missing callback for closing cancel modal after cancel action was successful
=> Fixed opened cancel modal after cancel was pressed.

src/helpers/order/order-helper.js, src/redux/action-types.js, src/redux/actions/order-actions.js, src/redux/reducers/order-reducer.js, src/smart-components/order/order-detail/approval-request.js
If there are no approval requests for order item, this spinner will show and it will call the API periodically every 3sec, until there are some.
=> Add autorefresh for approval requests in order detail screen.

src/presentational-components/portfolio/porfolio-card.js, src/routing/catalog-route.js, src/smart-components/portfolio/portfolios.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/toolbar/schemas/portfolio-toolbar.schema.js
Portfolio delete menu item enabled based on user permissions
=> Portfolio delete menu item enabled based on user permissions

src/App.js
jira: https://projects.engineering.redhat.com/browse/SSP-1344
The UI is trying to access the permissions data before the authentication finished.
That throws a rbac error and there are no permissions data set to the app context and the user gets kicked out to a 401 page.
The permission call now waits for the chrome to authorize the user.
=> Wait for chrome user authentication.

src/helpers/approval/approval-helper.js, src/presentational-components/shared/pf4-select-wrapper.js, src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap, src/test/smart-components/common/edit-approval-workflow.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-924
Select expects its initial values to be included in the first `loadOptions` call. That is required due to incomplete information it gets. Initial values are just literals but options are objects with value and label. So if the initial value is not in options it gets removed. And because API returns only first 100 items, values from second pages were removed on the first render.
Now, the initial load options request for approval filters specifically for selected values alongside the rest of the options.
I tested it by limiting the workflow options request to one or two records.
=> Prefetch select initialValues on first render to avoid missing options.

src/smart-components/portfolio/portfolio-empty-state.js, src/test/smart-components/portfolio/portfolio-empty-state.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1362
- no permissions on add products button in portfolio empty state
@gmcculloug I've used `catalog:portfolio_items:create` for now. I expect that this will be a part of user capabilities later on. We should probably also prepare some messages for the users if they don't have permission to add portfolio items.
=> Fixed missing permissions for add products button.

src/helpers/portfolio/portfolio-helper.js, src/redux/actions/portfolio-actions.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js, src/test/smart-components/portfolio/portfolio.test.js
- remove unnecessary portfolio request
- portfolio item detail route is nested under portfolio route
- data about portfolio are available in store, there is no need for additional request
- fixate date now prototype method to always return certain date to avoid snapshot fails
=> Remove duplicate portfolio fetch

src/smart-components/order/order-detail/approval-request.js
jira: https://projects.engineering.redhat.com/browse/SSP-1375
So far the code checks if the order is Failed and has no approval requests. I do have a question about the possibility of having order in the completed state but with no approval requests. If that is possible, we need more information to determine whether the approval requests will eventually exist or if there are simply no requests.
=> Add empty state for order approvals.

src/helpers/shared/helpers.js, src/redux/reducers/portfolio-reducer.js, src/routing/catalog-route.js, src/smart-components/common/catalog-link.js, src/smart-components/common/edit-approval-workflow.js, src/smart-components/error-pages/common-api-error.js, src/smart-components/error-pages/error-redirects.js, src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/smart-components/portfolio/portfolio-item.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolio.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap, src/test/routing/catalog-route.test.js, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js, src/test/smart-components/portfolio/portfolio-item.test.js, src/test/smart-components/portfolio/portfolio.test.js
waiting for: https://github.com/RedHatInsights/catalog-ui/pull/475
jira: https://projects.engineering.redhat.com/browse/SSP-1372, https://projects.engineering.redhat.com/browse/SSP-1376
- added restrictions on portfolio items based on user capabilities
- added user capabilities check on catalog route
- fixed up some prop types errors
@lgalis @gmcculloug I used the portfolio item `destroy` capability do hide/show the checkbox for selecting the card. I know that @lgalis mentioned that it should be based on the portfolio `update` capability. Just want to double-check which one of these flags is the correct one,
=> Portfolio item user capabilities

package-lock.json, package.json, src/App.js, src/presentational-components/shared/loader-placeholders.js, src/router.js, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap, src/test/presentational-components/shared/loader-placeholders.test.js, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
a detailed description of the issue:  https://github.com/danilowoz/react-content-loader/issues/93
jira: https://projects.engineering.redhat.com/browse/SSP-1385
There are no visual changes
- safari browser is displaying black stripes in content loaders
- fix for safari broke chrome on Linux so I removed the library and implemented it using CSS
- CSS implementation should have much better browser support and is actually customizable
=> Replace react-content-loader with css implementation.

src/redux/reducers/portfolio-reducer.js
jira: https://projects.engineering.redhat.com/browse/SSP-1391
- the optimistic UI placeholders for portfolio when adding/removing did not include user_capabilities object which caused the UI to crash.
=> Add missing user_capabilities to portfolio placeholders.

src/presentational-components/styled-components/card.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
jira: https://projects.engineering.redhat.com/browse/SSP-1424
This issue was caused by a different order of loading CSS assets. PF css was loaded after the catalog styles, which meant it was overriding catalog styles. The `!important` flag should be an easy fix.
=> Fixed styled card body spacing.

src/redux/actions/portfolio-actions.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1417
- in portfolio item detail, use `selectedPortfolio` instead of assigning it to the `portfolioItem` in the action creator (portfolio might not exist at that point)
- there were issues with missing data if the request for portfolio item finished before the request for the selected portfolio
=> Use portfolio directly from selectedPortfolio in portfolio item detail.

src/presentational-components/styled-components/table.js, src/smart-components/order/order-item.js, src/smart-components/order/orders-list.js
jira: https://projects.engineering.redhat.com/browse/SSP-1428
- switched from data list to table in the orders view
- it does use PF styles and class names but no the react tabular version, just the elements (no need for the whole thing on static table)
- if the image is too large, it will be cropped but the aspect ration will be kept
=> Use table to force order title to be aligned.

src/redux/actions/order-actions.js, src/redux/actions/portfolio-actions.js, src/routing/uri-state-manager.js, src/routing/use-initial-uri-hash.js, src/smart-components/order/orders-list.js, src/smart-components/portfolio/portfolio.js, src/smart-components/portfolio/portfolios.js, src/smart-components/products/products.js, src/test/redux/actions/portfolio-actions.test.js, src/test/smart-components/portfolio/portfolio.test.js, src/test/smart-components/portfolio/portfolios.test.js, src/utilities/store.js, src/utilities/view-state-middleware.js
- added hash to URL which represents the filter state of certain pages
- allows for sharing exact view-state via URL
- for example, you can create a filter for completed orders with a specific user and bookmark it
- persistent URL is applied on portfolios, portfolio items (of some portfolio), orders and products list screens
- it can be added to any screen by adding some flags to redux action creators
- the view state is encoded via `atob (btoa)` and then added to hash part of URL. It is not sent to servers and it's not limited by 2083 character limit (give or take, depends on ob browser).
=> Encode view state to URL fragment

src/smart-components/platform/service-offering/service-offering-detail.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/presentational-components/portfolio/portfolio-card.test.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
Jira: https://projects.engineering.redhat.com/browse/SSP-1443
This PR updated the label text read "Created" rather than "Created at" on all relevant screens.
Old
New
=> Update "Created" label

src/helpers/shared/user-login.js
https://projects.engineering.redhat.com/browse/SSP-1256
For this PR - using the existing sentryId parameter to display the x-rh-insights-request-id.
This will be changed after the requestId parameter is added to the platform nootifications.
=> Add insights request id to the error notification

src/presentational-components/styled-components/table.js, src/smart-components/order/order-item.js
jira: https://projects.engineering.redhat.com/browse/SSP-1436
follow-up to: https://github.com/RedHatInsights/catalog-ui/pull/512
Changes introduced in the PR above allowed for cropping of product images when necessary, but also severely cropped them in the mobile layout where there's room. This PR excludes the "shrink" class from the mobile layout, resolving the issue.
Old (mobile)
New (mobile)
Old (desktop)
New (desktop)
=> Fix Order icon in mobile layout

src/global-styles.js, src/smart-components/platform/service-offering/service-offering-detail.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/smart-components/platform/service-offering/service-offering-detail.test.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
jira: https://projects.engineering.redhat.com/browse/SSP-1457
This PR updates the styling of fonts used for labels and values in the left column of the Service Offering & Portfolio Item Detail screens
It also makes the left column  responsive, eliminating the need for ellipsis to truncate text.
I'll follow-up with a styled-component later.
Old (desktop)
New (desktop)
Old (mobile)
New (mobile)
=> Detail screens text styling and responsiveness fix

src/global-styles.js, src/presentational-components/styled-components/toolbars.js
jira: https://projects.engineering.redhat.com/browse/SSP-1455
Extremely long names (without spaces) cause screen elements on the right to be pushed out of the viewport. Here, I used "overflow-wrap: anywhere", which will first attempt to wrap at a word break, failing that, it will break extremely long words where needed.  Since the breadcrumb and title are able to accommodate wrapping, it seemed like a better  approach than using an ellipsis.
/cc @sbuenafe-rh
Old
New
=> Long Portfolio name breaks the layout

src/smart-components/portfolio/portfolio-empty-state.js, src/smart-components/portfolio/portfolio-items.js, src/test/smart-components/portfolio/portfolio-empty-state.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1451
- use user capabilities instead of rbac permissions to show/hide add products to the portfolio in empty portfolio
=> Fixed missing add products to portfolio button.

src/global-styles.js, src/smart-components/platform/service-offering/service-offering-detail.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
jira: https://projects.engineering.redhat.com/browse/SSP-1457
follow-up to: https://github.com/RedHatInsights/catalog-ui/pull/531
The last PR (https://github.com/RedHatInsights/catalog-ui/pull/531)  made adjustments to the left column on the Service Offering & Portfolio screens to make them responsive and removed the ellipses, allowing wrapping at word breaks.
This PR forces long names without spaces to break where needed and adds proper padding between columns.
Before:
After:
=> Details screens responsiveness follow-up

src/global-styles.js, src/presentational-components/styled-components/toolbars.js
This PR adds a fallback for browsers that don't support the css property/value combination: "overflow-wrap: anywhere."
Instead of only creating a break if an entire word cannot be placed on its own line without overflowing, the fallback will break text anywhere neccessary.
Follow-up to: https://github.com/RedHatInsights/catalog-ui/pull/550
jira: https://projects.engineering.redhat.com/browse/SSP-1457
Most browsers
Safari
=> overflow-wrap fallback support for Safari

src/smart-components/order/orders-list.js
Added "Ordered" to the filter list and sorted the list alphabetically.
https://projects.engineering.redhat.com/browse/SSP-1485
Before:
After:
<help>  🙂
=> Added "Ordered" to the list of Order state filter options

src/helpers/order/order-helper.js, src/smart-components/order/order-detail/order-detail.js, src/smart-components/order/order-detail/order-details.js, src/test/smart-components/order/orders.test.js
Update order detail messages for deleted porfolio items
Fixes https://projects.engineering.redhat.com/browse/SSP-1409
Only display missing resource message for order detail resources we have the id of.
Before:
After:
=> Update order detail messages for deleted porfolio items

package-lock.json, src/presentational-components/portfolio/portfolio-card-header.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
Links on portfolio cards now have the actual PF link color like the rest of the cards in UI.
=> Fixed portfolio card link text color.

src/smart-components/order/order-detail/approval-request.js, src/test/smart-components/order/order-detail.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1498
- if the user tried to access the approval tab in order detail page, the UI could crash if no approval data was undefined. This can happen if some of the order data were deleted.
- Now it displays the same message as if no approval messages were created (empty array)
Can't show any screenshots right now, the qa.sso is dead and I can't log in to the platform.
- added condition to prevent rendering the approval messages list when the data is missing
=> Prevent order approval tab from crashing when data is missing.

src/presentational-components/portfolio/porfolio-card.js, src/smart-components/portfolio/portfolios.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/presentational-components/portfolio/portfolio-card.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1483
A portfolio can now be copied from the card menu.
=> Add copy option to portfolio card dropdown.

src/smart-components/products/products.js, src/test/smart-components/products/products.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1377
The add source button in products page empty state is only visible for org admins.
=> Hide add source button for non org admins on producst page

src/helpers/order/order-helper.js, src/smart-components/order/order-detail/approval-request.js, src/smart-components/order/order-detail/order-detail.js, src/smart-components/order/order-detail/order-details.js
jira: https://projects.engineering.redhat.com/browse/SSP-1311
- of an order item were missing in the order detail, it was causing and crash in the UI 
- all sub-requests for order detail page are now catching and ignoring 400 and 404 responses to avoid invoking the error notification
- UI will display the missing product notification
=> Ignore all 400 and 404 responses in order detail.

src/smart-components/error-pages/common-api-error.js, src/smart-components/order/order-detail/approval-request.js, src/test/smart-components/order/order-detail.test.js
Fix spelling for 'authorized' https://projects.engineering.redhat.com/browse/SSP-1495
Before:
After:
=> Check for approval request data and a small spelling fix

src/global-styles.js, src/presentational-components/shared/top-toolbar.js, src/presentational-components/styled-components/toolbars.js, src/smart-components/order/order-detail/order-detail.js, src/smart-components/order/order-item.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Jira:  https://projects.engineering.redhat.com/browse/SSP-1456
This PR fixes an issue on many of the screens where a long name causes buttons, kebabs and text links (on the right) to drop a line. It also insures that those elements are vertically aligned to the top.
Before
After
Before
After
Before
After
Before
After
=> Long names cause page elements to drop a line

src/App.js
Added missing CSS files to the catalog.
Turns out that we do need the frontend components CSS. It does work locally but not on proc.
Caused by last bundle size optimizations.
(I feel like I've done this before)
=> Add missing CSS

src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
jira: https://projects.engineering.redhat.com/browse/SSP-1533
- The portfolio was correctly updated but not stored in the redux store. That caused the old data to be shown even though the URL had the correct redirect information
- Also fixed a typo in disabling submit prop on the form
=> Fixed portfolio reload after copy product action.

src/helpers/order/order-helper.js, src/smart-components/order/order-detail/order-detail.js, src/test/smart-components/order/orders.test.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1534
1. Fixes the order of the array of promises in getOrderDetails.
2. If the portfolio item is missing, only display the message for that, not for the platform or portfolio
=> Update order for the getOrderDetail promises

src/presentational-components/styled-components/table.js, src/smart-components/order/order-item.js
jira: 
https://projects.engineering.redhat.com/browse/SSP-1494
https://projects.engineering.redhat.com/browse/SSP-1500
In this PR, the left column of the order screen is fixed at 200 pixels (for desktop layout), rather than 10%. This resolved the scaling/cropping problems of images that are very wide (and unreadable when scaled down or cropped.)  I also removed the  left margin from the image in the mobile layout, which had been pushing the image too far right.
=> Adjust order screen image formatting

src/smart-components/order/order-detail/order-detail.js
Follow up to https://github.com/RedHatInsights/catalog-ui/pull/582
Add the 'for this order' to the message
=> Fixed missing order resources message

src/global-styles.js
jira: https://projects.engineering.redhat.com/browse/SSP-1529
This PR removes the vertical scrollbar present in all modal bodies.
Before: 
After:
=> eliminate unneeded scrollbar from modals

src/smart-components/error-pages/error-redirects.js, src/test/routing/catalog-route.test.js, src/test/smart-components/portfolio/add-portfolio-modal.test.js, src/test/smart-components/portfolio/portfolio.test.js, src/test/smart-components/portfolio/remove-portfolio-modal.test.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js
- use 403  route as a default for unauthorized redirects
- 401 is for authentication issues, we do not want to communicate to the user that he should log in
- 403 is for authorization issues, we know who the user is, we just simply tell him that they do not have the authorization do some action
=> Use 403 as a default unauthorized route.

package-lock.json, package.json, src/utilities/view-state-middleware.js
- use replace history method when appending hash to pathname for the first time
- before it took several goBack actions to actually navigate to previous valid view
- the sequence looked something like this when navigating back from portfolios to products:
```
/portfolios#viewStateHash -> /portfolios -> /products#hash
```
- now it skips the middle step which is only temporary
```
/portfolios#viewStateHash -> /products#hash
```
=> Improve the viewState hash routing

config/webpack.config.js, package-lock.json, package.json, profiles/local-frontends.js
In preparation for service workes and browser caching and pre-loading of the assets, we need to ensure that w have unique asset names in order to be able to use the most aggressive and efficient cache strategy.
The webpack `contentHash` generates a unique hash based on the file contents. This should allow us to use the `CacheFirst` service worker cache strategy.
I've also had to adjust the spadnx confix because we were missing the root override `/anasible/catalog` and it was serving the old `App.js` and `index.html` directly from ci.cloud and not the localhost.
=> Add a hash to JS bundles

src/smart-components/platform/platforms.js, src/smart-components/products/products.js
Change "Catalog sources" to "Sources"
The settings area only shows a "Sources" link.
I believe "Catalog sources" was the text being used before the Sources UI moved to the global gear icon.
Before
After:
=> Update Sources link text to match UI

src/forms/edit-workflow_form.schema.js, src/smart-components/common/edit-approval-workflow.js, src/test/smart-components/common/edit-approval-workflow.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1539
This PR set the modal title to the generic "Set Approval" and moves the full portfolio name into the body of the modal (just like "Share Portfolio".)  This allows long portfolio names to wrap properly.
Before
After
=> Update "set approval" modal

package-lock.json, package.json, src/forms/edit-portfolio-item-form.schema.js, src/forms/edit-workflow_form.schema.js, src/forms/form-fields/shage-group-edit.js, src/forms/form-fields/share-group-select.js, src/forms/portfolio-form.schema.js, src/presentational-components/shared/filter-select.js, src/presentational-components/shared/pf4-select-wrapper.js, src/smart-components/common/form-renderer.js, src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js, src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js, src/smart-components/survey-editing/survey-editor.js, src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap, src/test/forms/portfolio-form.schema.test.js, src/test/integration/portfolio-integration.test.js, src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap, src/test/presentational-components/shared/pf4-select-wrapper.test.js, src/test/smart-components/common/edit-approval-workflow.test.js, src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js
It can wait for weeks. Just putting it out there so we won't forget: https://github.com/RedHatInsights/catalog-api/pull/671
Currently, there are components with old keys in the component mapper to serve as a bridge between the new version of DDF and older schemas in DB.
Redundant components and validators should be removed after DB migration.
=> Update ddf to v2.

config/webpack.config.js, package-lock.json, package.json, src/Routes.js, src/smart-components/dialog-routes/index.js, src/smart-components/dialog-routes/platform-routes.js, src/smart-components/dialog-routes/portfolio-routes.js, src/smart-components/order/order-detail/order-detail.js, src/smart-components/platform/platform-inventories.js, src/smart-components/platform/platform-templates.js, src/smart-components/platform/platform.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolio.js, src/smart-components/portfolio/portfolios.js, src/test/integration/portfolio-integration.test.js, src/test/smart-components/platform/platform-inventories.test.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js, src/test/smart-components/portfolio/portfolio.test.js
- overall bundle size reduced to 3.06MB from 3.5MB
- optimized code splitting
- it's now more optimized for HTTP2 transport which is enabled on prod env
- benefits from parallel asset fetching and will be even faster after the service worker is up and running
- PF assets are deduped and are now forced to live in the same chunk(s)
- Almost all of the size savings come from PF optimizations. Lots of PF components were duplicated across multiple chunks
- Added lazy loading to nested routes
- Added common routes to modal routes
- removed duplicate imports in multiple files for models that can be opened from multiple entry points
Routes splitting:
=> Improve code splitting across the APP

src/smart-components/survey-editing/survey-editor.js
jira: https://projects.engineering.redhat.com/browse/SSP-1616
- force to create a new instance of survey editor when the survey was reset
- this is a hacky solution, the core of the problem is inside the react final form library and has to be fixed there or we need to find a different state manager
=> Fix survey editor not propagating reset changes.

src/helpers/order/order-helper.js, src/presentational-components/order/order-notification.js, src/redux/actions/order-actions.js, src/smart-components/common/order-modal.js, src/test/redux/actions/order-actions.test.js, src/test/smart-components/common/order-modal.test.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1629?workflowName=Software+Simplified+Workflow+for+Project+HSDM1&stepId=1
user should end on the order detail screen, not on the list of all orders screen
=> Redirect to oder detail from order success notification.

src/presentational-components/shared/loader-placeholders.js, src/smart-components/platform/platform.js, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
- added small toolbar placeholder when switching between platform templates and inventories
- removes the ugly popping of the toolbar after the JS chunk is loaded for the first time
- transition is a bit easier on the eye
=> Add platform detail toolbar loader.

src/smart-components/common/catalog-breadcrumbs.js, src/smart-components/common/catalog-link.js, src/test/smart-components/common/catalog-breadcrumbs.test.js
After the PF upgrade, custom breadcrumbs child components (which have to be used always in order to enable client-side routing) no longer receive a separator icon.
- `showDivider` prop is explicitly set
- `showDivider` prop is no excluded from catalog link, breadcrumbs are forcing this prop to all of its children and we can no longer safely just pass props to the actual link element
=> Fixed missing breadcrumbs separator

src/presentational-components/styled-components/toolbars.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1656
Before:
After:
=> Fix Platform toolbar after the PF4 v4 upgrade

src/presentational-components/portfolio/porfolio-card.js, src/presentational-components/styled-components/card.js, src/redux/reducers/portfolio-reducer.js, src/test/integration/portfolio-integration.test.js, src/test/integration/portfolio-item-integration.test.js, src/test/integration/portfolio-share-workflow.test.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/presentational-components/portfolio/portfolio-card.test.js, src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap, src/test/redux/reducers/portfolio-reducer.test.js, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap, src/test/smart-components/portfolio/add-portfolio-modal.test.js, src/test/smart-components/portfolio/portfolio.test.js, src/test/smart-components/portfolio/portfolios.test.js, src/test/smart-components/portfolio/remove-portfolio-modal.test.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-901
mock: https://marvelapp.com/prototype/625jh26/screen/58833387?
I was unable to use the green label because it was missing the background for some reason. I suppose its a bug in current PF version used in chrome :shrug: 
I've used the blue for now but we know that the colors may change and its an easy workaround if we need to force the color to be green.
=> Add shared label

.eslintrc, .gitignore, package-lock.json, package.json, src/redux/actions/approval-actions.js, src/redux/actions/portfolio-actions.js, src/smart-components/order/order-detail/order-detail.js
jira: https://projects.engineering.redhat.com/browse/SSP-1652
To create messages json run `npm run extract:messages` or `yarn extract:messages`.
A new file with messages will be created in `./translations/messages.json`. It is ignored from the repository since we don't know how and where to send these for translation.
It looks like something likes this:
```json
[
{
"id": "workflows.update_workflows.unlink",
"defaultMessage": "{count, number} {count, plural, one {approval process was} other {approval processes were}} unlinked successfully."
},
{
"id": "workflows.update_workflows.link",
"defaultMessage": "{count, number} {count, plural, one {approval process was} other {approval processes were}} linked successfully."
},
{
"id": "portfolio.remove.portfolio-items",
"defaultMessage": "You have …
```
=> Add react intl messages scraper script

src/presentational-components/styled-components/toolbars.js, src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap, src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap, src/test/smart-components/order/__snapshots__/orders.test.js.snap, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap, src/toolbar/helpers.js, src/toolbar/schemas/add-products-toolbar.schema.js, src/toolbar/schemas/portfolio-toolbar.schema.js, src/toolbar/schemas/portfolios-toolbar.schema.js, src/toolbar/schemas/products-toolbar.schema.js, src/toolbar/toolbar-mapper.js
There was an issue with underlying PF toolbar components. [Fix for platform toolbars](https://github.com/RedHatInsights/catalog-ui/pull/645) distorted the rest of the toolbars. Change to the actual DOM is necessary to make it work on all pages.
- use new Toolbar component composition
- added wrap property to toolbar component
- added wrap property to toolbar group component (no idea why toolbar group is not wrapped by default)
=> Fixed outdated toolbar layout.

.travis/custom_release.sh
Requires the creation of a new `master-stable` branch in place of ci-stable and qa-stable.
cc @brahmanim
=> Update custom_release.sh to work with 4 branches

src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
jira: https://projects.engineering.redhat.com/browse/SSP-1665
- the select value was resetting when the portfolio item copy name changed
- the form state management was setting an initial value to the copy name each time the name was changed, that caused a change of form global initial values leading to form re-initialization leading to dressing the form to its initial state and resetting the select value to initial value was always the value of the currently selected portfolio
- the initial name value was never even used since the value was always set by the select component, or when the form was initially mounted thus re-writing the initial value
- fixed by removing the initial value
=> Fixed copy select reset

src/helpers/order/order-helper.js, src/messages/orders.messages.js, src/messages/states.messages.js, src/smart-components/order/order-detail/approval-request.js, src/smart-components/order/order-detail/order-detail.js, src/smart-components/order/order-detail/order-details.js, src/smart-components/order/order-detail/order-lifecycle.js
wait for #663 
jira: https://projects.engineering.redhat.com/browse/SSP-1673
###Changes
- update the approval tab according to new design
cc @sbuenafe-rh @fionayhlin
I do have a couple of questions for our UX team.
- I see that the updated date for approval on mocks is using the exact value, but we have been using the relative date everywhere else. So should it bee relative or exact
- There was an icon for the completed request. Do we have icons for the rest of the request states?
- And what about the lifecycle tab? Currently, there is just the link. Are there any changes to that tab?
=> Order detail cards

src/global-styles.js
This PR adds space between the filter and pagination in the mobile layout
Jira: https://projects.engineering.redhat.com/browse/SSP-1628
Old
New
=> mobile order screen styling fix

package-lock.json, package.json, src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1668
- updated data-driven forms dependency
- the select component now calculates the distance to the button edge of the window and adds scrollbar if the menu overflows
- the menu is cropped if it should overflow the top edge of the first scrollable parent element (can't do the same for the bottom because the menu is supposed to overflow, we would have to come up with some rule of closing the menu)
- removed falsey expect
- select component when selecting platforms is not async and does not support async platforms loading.
@gmcculloug @eclarizio it would be great if we could cherry-pick this change to the ci-stable branch so the buggy version won't make it to the prod on 7/30.
=> Update DDF to fix select menu glitches.

src/presentational-components/portfolio/porfolio-card.js, src/presentational-components/portfolio/portfolio-card-header.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
This PR moves the  Product count out of the card title and into a badge
jira: https://projects.engineering.redhat.com/browse/SSP-1707
Old
New
=> Portfolio card count fix

src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
jira: https://projects.engineering.redhat.com/browse/SSP-1715
- the route for edit workflows was "eaten" by different component so the form did not even mount
- component with the modal has now the top priority
- removed the buttons route restrictions
- toolbar buttons are no longer hiding if the user is another route than `/portfolio/portfolio-item`
=> Give product set approval component higher priority.

src/redux/actions/portfolio-actions.js, src/smart-components/common/edit-approval-workflow.js, src/smart-components/dialog-routes/portfolio-routes.js, src/smart-components/portfolio/share-portfolio-modal.js, src/test/redux/actions/portfolio-actions.test.js, src/test/smart-components/common/edit-approval-workflow.test.js, src/test/smart-components/platform/platform-inventories.test.js, src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js, src/test/smart-components/portfolio/share-portfolio-modal.test.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1676
- `share` and `setApproval` modals depend on `selectedPortfolio`, however this value was not filled in the list. So now the `routes` component check if there is `portfolio` query and if no portfolio is selected, it will select it automatically + if the portfolio is not in the store already, it's fetched (i.e. on access via URL).
- `removeQuery` prop does not exist, changed to `removeSearch`
**Before**
**After**
=> Set selectedPortfolio when changing portfolio query param

src/messages/states.messages.js
Introduced in the advanced filter for portfolios or #690 
jira: https://projects.engineering.redhat.com/browse/SSP-1726
We have to be very careful when moving messages around. This was a dynamically assigned value to the format message API. I think I will create a wrapper around that function to add keys to rich text translation and a fallback so it does not cause runtime crashes if the definition was not found.
=> Copy created messages to states messages

package-lock.json, package.json, src/forms/edit-workflow_form.schema.js, src/forms/form-fields/initial-chips.js, src/global-styles.js, src/smart-components/common/edit-approval-workflow.js, src/smart-components/common/form-renderer.js, src/test/smart-components/common/edit-approval-workflow.test.js, src/test/smart-components/platform/platform-inventories.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1682
- existing approval workflows are now inside a chip group
- existing approval workflows are no longer an initial value of the select
- select options are disabled if the option is present in the chip group
- the submit callback only sends necessary workflow ids
- if the user unlinks workflow and then picks the same from the select, that id is not passed to the API call.
=> Update edit workflow process modal

src/test/utilities/empty-data-middleware.test.js, src/utilities/empty-data-middleware.js
jira: https://projects.engineering.redhat.com/browse/SSP-1743
There was a missing fallback for cases that the `filters` key is not present inside the action metadata
=> Fix runtime error after deleting portfolio from detail.

package-lock.json
note: workbox plugin did not release a fix for the dev dependency and I can't bump the affecting dependency version manually in lock file because the vulnerability was fixed in a major release with breaking changes. We will have to wait for the workbox to fix it.
=> Fix major security vulnerabilities

src/smart-components/order/order-detail/order-detail-information.js, src/smart-components/order/order-item.js, src/smart-components/order/order-status-mapper.js
- Updates order labels icons and colors
- Adds missing labels to order details
=> update labels colors and icons

src/smart-components/common/order-modal.js
This PR updates the modal title and removes the product image
jira: https://projects.engineering.redhat.com/browse/SSP-1690
Before:
After:
=> order modal updates

src/smart-components/portfolio/portfolios.js
Reset the sorting direction to the default ( asc ) when filter/sorting chips are cleared.
Fixes https://projects.engineering.redhat.com/browse/SSP-1727
=> Fix sorting on filter chips reset

src/App.js
This should fix the hard UI crash.
The navigation method is no longer supported.
=> Remove deprecated insights navigation call.

src/helpers/portfolio/portfolio-helper.ts, src/messages/icon.messages.ts, src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js, src/smart-components/portfolio/portfolio-item-detail/icon-upload.js, src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
jira: https://issues.redhat.com/browse/SSP-1755
~~blocked by: https://github.com/RedHatInsights/catalog-api/pull/793~~
after clicking on the icon dropdown will appear with change/reset options:
cc @sbuenafe-rh I have stolen common patterns for multi icon operations actions. Feel free to change it later.
=> Enable reset portfolio item icon.

src/messages/icon.messages.ts, src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
addresses https://github.com/RedHatInsights/catalog-ui/pull/729#issuecomment-692049546
@sbuenafe-rh did you have something like this in mind? Or can you provide a simple image of the menu placement?
=> Update icon dropdown menu styling

src/helpers/order/order-helper.ts
Fixes https://issues.redhat.com/browse/SSP-1808
Updated the graphql query to get the request and subrequests create dates. Use these for Updated column when the actions array is empty.
Before:
After:
=> Fix update date for approval request list in the orders detail page

src/presentational-components/portfolio/porfolio-card.tsx, src/smart-components/common/order-modal.tsx, src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js, src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js, src/smart-components/portfolio/portfolio-items.js, src/smart-components/portfolio/portfolios.js, src/test/presentational-components/portfolio/portfolio-card.test.js, src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap, src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js, src/test/utilities/portfolio-toolbar.schema.test.js, src/toolbar/schemas/portfolio-toolbar.schema.js
Display the Set order processes menu item only if the user has permissions link order processes permission
Fixes https://issues.redhat.com/browse/SSP-1909
User without order process link permission:
User with order-processes link permission:
=> Display the Set order processes menu item only if the user has permissions

src/helpers/order/new-order-helper.ts, src/helpers/order/order-helper.ts, src/helpers/portfolio/portfolio-helper.ts, src/messages/orders.messages.ts, src/redux/action-types.ts, src/redux/actions/order-actions.tsx, src/redux/reducers/order-reducer.ts, src/smart-components/order/order-detail/order-detail-menu.tsx, src/smart-components/order/order-detail/order-detail.tsx, src/smart-components/order/order-detail/order-provision.tsx, src/test/smart-components/order/__snapshots__/order-provision.test.js.snap, src/test/smart-components/order/order-provision.test.js
Implements https://issues.redhat.com/browse/SSP-1918
- part 1 - show before/after/( if any) and product  order items in the provisioning tab
( part 2 - add progress messages for each - in the next PR)
=> Add order provision tab

.eslintrc, package-lock.json, package.json, src/helpers/order/new-order-helper.ts, src/helpers/order/order-helper.ts, src/messages/orders.messages.ts, src/smart-components/order/order-detail/order-provision.tsx, src/smart-components/order/order-detail/progress-messages.tsx
Implements the expanded details for the Provision tab: https://issues.redhat.com/browse/SSP-1918
Non - admin user - no expandable content with progress messages
=> Add progress messages to provision tab

src/helpers/order/new-order-helper.ts, src/redux/actions/order-actions.tsx, src/redux/reducers/order-reducer.ts, src/smart-components/order/order-detail/order-provision.tsx
The progress message data no longer contains the order id.
This PR separates the progress messages per order item on fetch.
Fixes https://issues.redhat.com/browse/SSP-1956
Before:
After:
=> Separate progress messages for order items on fetch 

src/messages/labels.messages.ts, src/presentational-components/portfolio/porfolio-card.tsx, src/smart-components/portfolio/portfolio-item.js, src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap, src/test/presentational-components/portfolio/portfolio-card.test.js, src/types/common-types.d.ts
https://issues.redhat.com/browse/SSP-1809
Mocks: https://marvelapp.com/prototype/625jh26/screen/58833387
Adds a label to indicate whether approval processes are set for the portfolio or product.
=> Add 'Approval process set' label to catalog objects cards

src/helpers/order/order-helper.ts, src/smart-components/order/order-status-mapper.tsx, src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap, src/utilities/constants.ts
https://issues.redhat.com/browse/SSP-2014
Update api path
Separate order progress messages
Add icon and color map entry for order 'Denied' status
Before:
After:
=> Update api path, separate order progress messages

src/smart-components/order/order-detail/approval-request.tsx, src/test/smart-components/order/orders.test.js, src/utilities/constants.ts
https://issues.redhat.com/browse/SSP-1859
Will discuss with UX about adding a refresh button to the 'No records' page 
Before - infinite loop for orders stuck on the 'Created' state:
After - number of retries limited.
=> Update approval request fetching refresh

src/helpers/shared/helpers.tsx, src/helpers/shared/user-login.ts, src/presentational-components/platform/platform-card.tsx, src/redux/actions/platform-actions.ts, src/smart-components/order/order-detail/approval-request.tsx, src/smart-components/platform/platforms.js
- Add delay in re-enabling the platform refresh button after the refresh started
- Handle 429 as refresh in progress
- Add platform version and tower version to the platform card
429 error:
While refresh is runnig:
=> More platform refresh changes

src/presentational-components/platform/platform-card.tsx, src/smart-components/platform/platform.js, src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap, src/toolbar/schemas/platforms-toolbar.schema.js
Remove the Enabled label from the platform card and teh platform summary page. ( Disabled platforms are hidden)
=> Remove the Enabled label from the platform card and the platform summary page

package.json
Previously, only javascript files were being checked for strings by the `npm run extract:messages` command, which resulted in 2 or 3 dummy strings in `./translations/messages.json`.  This change does the following:
* checks typescript files in addition
* excludes `*.d.ts` files as they cause formatjs to fail
Example of previous error:
```
[chadams@chadams-work catalog-ui]$ npx @formatjs/cli extract 'src/**/*.{js,jsx,ts,tsx}' --out-file ./translations/messages.json
npx: installed 68 in 10.857s
[@formatjs/cli] [WARN] Error: Error processing file src/index.d.ts 
Debug Failure. Output generation failed
```
Now all of the strings are extracted as expected.  The strings end up here:
```
$ tree ./catalog-ui/translations/
translations/
└── messages.json
```
```
$ cat translations/messages.json | …
```
=> Extract l10n messages for typescript files, but excluding .d.ts files

.github/workflows/dist-release.yml
https://issues.redhat.com/browse/SSP-2710
Right now the latest dev release workflow is not working because [the latest release already exists](https://github.com/RedHatInsights/catalog-ui/runs/5054260855?check_suite_focus=true#step:6:14). 
There are two commits:
- apply the right format
- delete the release before publish
=> Fix dev release
